/* Adventure Family — testi in italiano chiaro, da leggere ad alta voce. */
(function (root) {
  const C = {};

  C.worlds = [
    { id: "w-lucciole", name: "il Bosco delle Lucciole", hook: "È un bosco di notte. Le lucciole fanno luce a intermittenza: quando si spengono, per un attimo non si vede il sentiero." },
    { id: "w-nonna", name: "la Cucina Gigante", hook: "Siete piccoli come formiche in una cucina enorme. I mestoli sono alti come alberi e una pentola bolle come un lago." },
    { id: "w-isola", name: "l'Isola che Cammina", hook: "L'isola è sul guscio di una tartaruga enorme. Quando la tartaruga fa un passo, tutta la spiaggia trema." },
    { id: "w-soffitta", name: "la Soffitta dei Giochi Dimenticati", hook: "Siete in una soffitta piena di scatole. I peluche e i giochi vecchi si sono organizzati come in un piccolo paese." },
    { id: "w-tappeto", name: "la Città sotto il Tappeto", hook: "Sotto il tappeto c'è una città di briciole, bottoni e fili. Bisogna stare attenti a non inciampare nei peli." },
    { id: "w-caramello", name: "il Vulcano di Caramello", hook: "Dal vulcano esce caramello caldo invece della lava. È dolce, ma attacca le scarpe e fa cadere." },
    { id: "w-biblio", name: "la Biblioteca Infinita", hook: "I corridoi di libri non finiscono mai. Se chiudi un libro in modo sbagliato, la stanza cambia posto." },
    { id: "w-treno", name: "il Treno sulle Nuvole", hook: "Siete su un treno che viaggia tra le nuvole. Non si ferma: le stazioni si attaccano al convoglio mentre corre." },
    { id: "w-ombre", name: "il Mercato delle Ombre", hook: "In questo mercato si comprano ombre, echi e sbadigli. Si paga con una promessa, non con i soldi." },
    { id: "w-lago", name: "il Lago Ghiacciato al Contrario", hook: "Il ghiaccio sta sotto e l'acqua cammina sopra. Si può scivolare, e il mondo sembra a testa in giù." },
    { id: "w-specchio", name: "il Castello nello Specchio", hook: "Siete dentro uno specchio. I riflessi si muovono da soli e non sono sempre d'accordo con voi." },
    { id: "w-fattoria", name: "la Fattoria delle Notti Corte", hook: "Qui il sole tramonta in pochi minuti. Bisogna fare in fretta, perché la notte arriva all'improvviso." },
    { id: "w-sale", name: "il Deserto di Sale", hook: "Il suolo è tutto di sale croccante. Se corri troppo, il rumore chiama le tempeste di cristalli." },
    { id: "w-porto", name: "il Porto dei Pesci Volanti", hook: "Le barche sono legate alle nuvole. I pesci volano e litigano con i gabbiani per un posto sul molo." },
    { id: "w-gatti", name: "il Giardino dei Gatti Giardinieri", hook: "I gatti curano le piante. Se innaffi nel modo sbagliato, le piante miagolano e i gatti si offendono." },
    { id: "w-miniera", name: "la Miniera di Stelle Cadute", hook: "Sotto terra si scava la luce delle stelle. Se ne prendi troppa, sopra arriva una notte più buia del normale." },
    { id: "w-pozzo", name: "il Paese dentro il Pozzo", hook: "Si scende nel pozzo e si trova un paese capovolto: i tetti sono le strade e i camini sono le porte." },
    { id: "w-circo", name: "il Circo Fermo da Cent'anni", hook: "Il tendone c'è ancora, ma il pubblico è sparito. Qualche gioco del circo funziona da solo, e fa paura un po'." },
    { id: "w-scuola", name: "la Scuola di Magie Sbagliate", hook: "Ogni incantesimo fa l'opposto di quello che dovrebbe. I diari scappano e i gessetti scrivono da soli." },
    { id: "w-giganti", name: "la Valle dei Giganti Addormentati", hook: "I giganti dormono per terra. Il loro russare è vento. Camminare sul naso di uno è l'unico modo per attraversare." },
    { id: "w-te", name: "il Villaggio nella Tazza da Tè", hook: "Siete in un villaggio sul bordo di una tazza enorme. Quando qualcuno sorseggia il cielo, il tè sale e allaga le strade." },
    { id: "w-divano", name: "i Cunicoli sotto il Divano", hook: "Sotto il divano ci sono calzini persi, monete e un re dei popcorn. È stretto, polveroso e pieno di nascondigli." },
    { id: "w-faro", name: "il Faro sulla Luna Bassa", hook: "La luna si è fermata vicino al molo, come una barca. Il faro gira al contrario e illumina il mare di sopra." },
    { id: "w-ombrelli", name: "la Foresta di Ombrelli", hook: "Al posto degli alberi ci sono ombrelli. Quando piove si aprono da soli e coprono proprio il sentiero sbagliato." }
  ];

  C.quests = [
    { id: "q-uovo", name: "Riportare l'Uovo dei Compleanni", goal: "l'Uovo dei Compleanni. Se manca, nel paese nessuno ricorda i compleanni e non si festeggia più" },
    { id: "q-chiave", name: "Ritrovare la Chiave del Domani", goal: "la Chiave del Domani, che apre solo i giorni che devono ancora arrivare. Senza di lei il calendario si blocca" },
    { id: "q-ricetta", name: "Riprendere la Ricetta del Coraggio", goal: "la Ricetta del Coraggio. Senza di quella le merende non danno più forza e tutti hanno paura per niente" },
    { id: "q-ombra", name: "Riportare l'Ombra del Paese", goal: "l'ombra di tutto il paese. Senza ombra nessuno riesce a fare il pisolino, perché c'è troppa luce" },
    { id: "q-bussola", name: "Raddrizzare la Bussola dei Sogni", goal: "la Bussola dei Sogni, che punta verso chi ha bisogno di aiuto. Ora gira a caso e nessuno sa dove andare" },
    { id: "q-drago", name: "Consegnare la Lettera al Drago Timido", goal: "una lettera importante. Se non arriva al drago, lui piange e le nuvole restano grigie per una settimana" },
    { id: "q-orologio", name: "Riavvolgere l'Orologio della Cena", goal: "l'Orologio della Cena. Decide quando si torna a tavola: se resta rotto, si cena a mezzanotte o mai" },
    { id: "q-seme", name: "Piantare il Seme dell'Ultima Risata", goal: "un seme magico. Se lo piantate, cresce una risata capace di spegnere le paure del paese" },
    { id: "q-mappa", name: "Ricucire la Mappa Strappata", goal: "la mappa del territorio. Senza di lei i sentieri si mischiano e si finisce sempre nel posto sbagliato" },
    { id: "q-corona", name: "Nascondere la Corona Inutile", goal: "una corona che rende re chiunque la metta, anche un cappello. Va nascosta prima che la metta il cattivo" },
    { id: "q-lume", name: "Accendere il Lume dei Persi", goal: "un lume che mostra la strada a chi si è perso. Ora è spento e la gente gira in tondo" },
    { id: "q-patto", name: "Spezzare il Patto delle Scorciatoie", goal: "un patto magico che fa arrivare prima, ma toglie i dolci del ritorno. Va spezzato per riportare le cose a posto" },
    { id: "q-canto", name: "Restituire la Voce alle Campane", goal: "il canto delle campane. Qualcuno l'ha rubato: ora sono mute e il paese non sa più che ora è" },
    { id: "q-ponte", name: "Ricostruire il Ponte delle Scuse", goal: "il ponte su cui si passa solo se si è detto davvero scusa. È crollato e le due rive non si parlano più" },
    { id: "q-gatto", name: "Liberare il Gatto Archivista", goal: "il gatto che tiene in ordine i nomi di tutti. Se resta prigioniero, la gente dimentica come si chiama" },
    { id: "q-neve", name: "Fermare la Neve di Farina", goal: "il modo per fermare una bufera di farina. Sta seppellendo i forni e non si può più fare il pane" },
    { id: "q-specchio", name: "Chiudere lo Specchio Ingordo", goal: "lo specchio che ruba i volti se lo guardi troppo. Va chiuso prima che resti qualcuno senza faccia" },
    { id: "q-nave", name: "Varare la Nave di Carta", goal: "una nave di carta magica. Porta a casa chi è rimasto fuori troppo tardi" },
    { id: "q-lanterna", name: "Riempire la Lanterna di Storie", goal: "una lanterna che si accende solo se le racconti una storia vera. Senza luce, la notte è troppo lunga" },
    { id: "q-treno", name: "Fermare il Vagone Birichino", goal: "un vagone che scappa da solo e porta via i pisolini della gente" },
    { id: "q-re", name: "Svegliare il Re delle Pause", goal: "il re che decide quando si fa merenda. Se dorme troppo, nessuno si ferma più a mangiare" },
    { id: "q-colore", name: "Restituire il Rosso al Tramonto", goal: "il colore rosso rubato ai tramonti. Ora il cielo di sera è grigio e il paese è triste" },
    { id: "q-chiave2", name: "Aprire il Baule dei Sì", goal: "il baule dove sono chiusi i permessi di «giocare ancora un po'». Senza di quelli si torna sempre dentro troppo presto" },
    { id: "q-vento", name: "Calmare il Vento Pettegolo", goal: "il vento che racconta i segreti in piazza. Va calmati prima che metta tutti gli uni contro gli altri" }
  ];

  C.villains = [
    { id: "v-conte", name: "il Conte dei Minuti", style: "ruba il tempo: le giornate finiscono troppo presto e non si fa in tempo a giocare" },
    { id: "v-strega", name: "Strega Brodo", style: "cuoce i piani degli altri in una pentola e li serve freddi, così i vostri piani non funzionano" },
    { id: "v-re", name: "Re Tappo", style: "chiude tutto con dei tappi: porte, camini, risate. Vuole che nessuno esca e nessuno si diverta" },
    { id: "v-ombra", name: "la Signora Senza Ombra", style: "ruba le ombre degli altri perché si sente sola. Chi resta senza ombra ha sempre freddo" },
    { id: "v-mago", name: "Mago Sbagliato il Grande", style: "lancia incantesimi al contrario di proposito: se chiedi luce, fa buio" },
    { id: "v-lupo", name: "il Lupo dei Cuscini", style: "soffoca le avventure sotto pile di cuscini: ti addormenta quando dovresti agire" },
    { id: "v-capitano", name: "Capitano Muffa", style: "fa ammuffire i tesori e le buone idee. Quello che tocca diventa inutile" },
    { id: "v-bambola", name: "la Bambola Direttore", style: "vuole dirigere tutti come burattini, con un sorriso fisso. Se obbedisci, non scegli più tu" },
    { id: "v-cuoco", name: "Chef Fulmine", style: "cucina tempeste e le tira addosso senza chiedere. Odia chi entra in cucina senza permesso" },
    { id: "v-bibliotecaria", name: "la Bibliotecaria del Silenzio", style: "cancella le parole dette troppo forte. Se parli, rischi di restare senza voce" },
    { id: "v-nano", name: "il Nano delle Scorciatoie", style: "vende strade corte che finiscono nel cespuglio sbagliato. Vuole farvi perdere tempo" },
    { id: "v-gatto", name: "Gatto Imperatore", style: "esige tributi: nascondini obbligatori e fusa a comando. Chi non obbedisce viene graffiato (da fiaba)" },
    { id: "v-gelataio", name: "il Gelataio Gelido", style: "congela i piedi e i ripensamenti. Chi lo incontra resta fermo sul posto" },
    { id: "v-pittore", name: "il Pittore delle Porte False", style: "dipinge uscite che non esistono. Segui una porta dipinta e sbatti contro il muro" },
    { id: "v-sarto", name: "il Sarto delle Ombre Strette", style: "cuce vestiti che stringono: una volta indossati, ti costringono a fare quello che vuole lui" },
    { id: "v-posta", name: "il Postino dei No", style: "consegna solo rifiuti e mai i «sì». Le lettere importanti non arrivano mai" },
    { id: "v-rana", name: "Rana Sindaca", style: "fa votare le pozzanghere contro i viaggiatori. Vuole che restiate fuori dal paese" },
    { id: "v-drago", name: "il Drago degli Sbadigli", style: "addormenta intere valli con uno sbadiglio. Chi sbadiglia con lui si addormenta sul più bello" },
    { id: "v-specchio", name: "il Gemello nello Specchio", style: "copia i vostri gesti e li fa un po' più cattivi, per farvi passare dalla parte del torto" },
    { id: "v-mulo", name: "Mulo Doganiere", style: "blocca la strada e chiede pedaggi in calzini spaiati. Senza pedaggio non si passa" },
    { id: "v-luna", name: "la Luna Storta", style: "tira le maree e anche i calzini sotto i letti. Di notte sposta le cose apposta per farvi inciampare" },
    { id: "v-sacco", name: "il Sacco dei Rimpianti", style: "inghiotte gli oggetti che dite «lo prendo dopo». Poi quegli oggetti non ci sono più" },
    { id: "v-coro", name: "il Coro dei «Non si può»", style: "canta regole finché nessuno osa più muoversi. Vuole che restiate fermi e zitti" },
    { id: "v-reclock", name: "l'Orologiaio Invertito", style: "fa scorrere i pomeriggi all'indietro. Così non arrivate mai all'ora giusta" }
  ];

  C.treasures = [
    { id: "t-fischietto", name: "il Fischietto dei Sussurri (chi lo usa viene ascoltato anche da lontano)" },
    { id: "t-calza", name: "la Calza che Cammina da Sola (può andare a prendere le cose)" },
    { id: "t-mela", name: "la Mela della Verità (a mezzogiorno risponde a una domanda in modo onesto)" },
    { id: "t-chiave", name: "la Chiave Storta (apre una porta sola, ma quella giusta)" },
    { id: "t-pennello", name: "il Pennello di Nebbia (disegna un nascondiglio di nebbia per un minuto)" },
    { id: "t-tazza", name: "la Tazza Quasi Senza Fondo (c'è sempre un sorso per chi ha sete)" },
    { id: "t-dado", name: "il Dado con un Sette (una volta a partita puoi ritirare un dado)" },
    { id: "t-cappa", name: "la Cappa delle Pause (chi la indossa può fermarsi e respirare senza essere visto)" },
    { id: "t-lanterna", name: "la Lanterna Pettegola (illumina e racconta se qualcuno si sta avvicinando)" },
    { id: "t-corda", name: "la Corda dei Bugiardi (si annoda da sola se qualcuno sta mentendo)" },
    { id: "t-pane", name: "il Pane dei Tre Giorni (sfama il gruppo e tiene un piccolo segreto dentro)" },
    { id: "t-specchio", name: "lo Specchietto dei Dietro (mostra cosa succede alle vostre spalle)" },
    { id: "t-sasso", name: "il Sasso che Torna in Tasca (lo puoi lanciare e poi lo ritrovi)" },
    { id: "t-piuma", name: "la Piuma Pesante (sembra leggera, ma tiene ferma una porta)" },
    { id: "t-orologio", name: "l'Orologio che Ritarda i Guai (i problemi arrivano un po' dopo, e vi dà tempo)" },
    { id: "t-mappa", name: "la Mappa che Starnutisce (starnutisce quando state sbagliando strada)" },
    { id: "t-anello", name: "l'Anello di Spago Magico (diventa una corda lunga quando serve)" },
    { id: "t-foglio", name: "il Foglio delle Scuse (scrive da solo una scusa onesta, se la pensate davvero)" },
    { id: "t-campana", name: "la Campanella dei Ritrovamenti (suona vicino alle cose perse)" },
    { id: "t-seme", name: "il Seme Instant-Albero (piantato, diventa una scala di rami in un minuto)" },
    { id: "t-guanti", name: "i Guanti da Nuvole (permettono di afferrare una nuvola e tirarsi su)" },
    { id: "t-bussola", name: "la Bussola dei Dolci (punta verso il cibo, e a volte verso la via d'uscita)" },
    { id: "t-sacco", name: "il Sacchetto di Briciole (non finisce mai: si può lasciare una traccia per tornare indietro)" },
    { id: "t-corona", name: "la Coroncina di Cartone (chi la mette viene ascoltato per tre frasi, anche dal cattivo)" }
  ];

  C.npcs = [
    { id: "n-talpa", name: "la Talpa Cartografa", quirk: "disegna mappe col naso e conosce i cunicoli" },
    { id: "n-nonno", name: "Nonno Nebbia", quirk: "ricorda cose che devono ancora succedere, ma dimentica le scarpe" },
    { id: "n-owl", name: "la Civetta Postina", quirk: "consegna le lettere, a volte al ramo sbagliato, ma si impegna" },
    { id: "n-bimbo", name: "il Bambino di Fumo", quirk: "è fatto di vapore e ha paura dei sospiri forti" },
    { id: "n-cuoca", name: "la Cuoca dei Minuti", quirk: "misura tutto in cucchiai di tempo e sa quando sbrigatevi" },
    { id: "n-cane", name: "il Cane Lanterna", quirk: "ha la coda che fa luce, ma si spegne se ha paura" },
    { id: "n-sarta", name: "la Sarta delle Nuvole", quirk: "rappezza i buchi nel cielo con toppe di lino" },
    { id: "n-pescatore", name: "il Pescatore di Echi", quirk: "pesca i suoni caduti nei pozzi e li può ridare indietro" },
    { id: "n-regina", name: "la Regina delle Formiche Fornaie", quirk: "offre briciole in cambio di notizie" },
    { id: "n-robot", name: "la Stufetta Parlante", quirk: "scalda i piedi e i discorsi troppo freddi" },
    { id: "n-albero", name: "l'Albero Impaziente", quirk: "sbatte i rami se aspettate troppo" },
    { id: "n-topo", name: "il Topo Bibliotecario", quirk: "timbra i visitatori sulla caviglia e sa dov'è ogni libro" },
    { id: "n-fata", name: "la Fata dei Compiti", quirk: "aiuta solo chi ha già provato almeno tre volte" },
    { id: "n-guardia", name: "la Guardia di Paglia", quirk: "è severa, ma si piega se le chiedete scusa per davvero" },
    { id: "n-mercante", name: "il Mercante di Sbadigli", quirk: "vende un po' di riposo, a rate" },
    { id: "n-lumaca", name: "la Lumaca Corriera", quirk: "è lenta, ma non sbaglia mai un indirizzo" },
    { id: "n-pirata", name: "il Pirata in Pensione", quirk: "ha una nave in una bottiglia e tanta nostalgia" },
    { id: "n-stella", name: "la Stella Caduta Zoppa", quirk: "zoppica di luce e chiede una spalla per camminare" },
    { id: "n-fornaio", name: "il Fornaio dei Sogni", quirk: "inforna gli incubi e li fa diventare crostate" },
    { id: "n-rana", name: "la Rana Notaia", quirk: "fa firmare i patti con una zampata bagnata" },
    { id: "n-ombra", name: "un'Ombra Smarrita", quirk: "cerca il suo padrone e si attacca al primo sorriso gentile" },
    { id: "n-drago", name: "un Draghetto Raffreddato", quirk: "starnutisce fiammelle innocue, ma molto rumorose" },
    { id: "n-nonna", name: "Nonna delle Chiavi", quirk: "ha tutte le chiavi tranne quella che serve in quel momento" },
    { id: "n-vento", name: "il Vento Apprendista", quirk: "sta ancora imparando a soffiare dritto" },
    { id: "n-statua", name: "la Statua che si Annoia", quirk: "commenta i passanti, ma solo se la salutate" },
    { id: "n-ape", name: "l'Ape Archivista", quirk: "cataloga i fiori e anche i favori che vi deve la gente" },
    { id: "n-re", name: "il Re dei Calzini", quirk: "governa un cassetto e cerca il paio perduto" },
    { id: "n-fantasma", name: "il Fantasma della Merenda", quirk: "appare solo tra le quattro e le cinque" },
    { id: "n-ponte", name: "il Ponte Parlante", quirk: "fa pagare il passaggio con una barzelletta" },
    { id: "n-gatto", name: "il Gatto Senza Nome", quirk: "accetta un nome solo se è sbagliato di proposito" },
    { id: "n-orologiaio", name: "l'Orologiaia dei Pisolini", quirk: "aggiusta i sonnellini che scappano" },
    { id: "n-mulo", name: "il Mulo Poeta", quirk: "recita versi se qualcuno gli porta una mela" }
  ];

  C.roles = [
    { id: "r-esplora", name: "Esploratore", knack: "sa trovare la strada anche quando è buio" },
    { id: "r-cuoco", name: "Cuoco di viaggio", knack: "sa inventare un pasto e fare pace con chi è di cattivo umore" },
    { id: "r-inventa", name: "Inventore da tasca", knack: "costruisce un aggeggio con tre oggetti qualsiasi" },
    { id: "r-parla", name: "Ambasciatore", knack: "sa convincere chi è arrabbiato" },
    { id: "r-guarda", name: "Sentinella", knack: "nota i dettagli che gli altri non vedono" },
    { id: "r-cura", name: "Guaritore", knack: "sistema i graffi e i piccoli guai" },
    { id: "r-furbo", name: "Birichino", knack: "sa distrarre, scivolare via e sparire un attimo" },
    { id: "r-forza", name: "Spalla forte", knack: "spinge, solleva e fa da ponte" },
    { id: "r-canto", name: "Cantastorie", knack: "cambia l'umore di un posto raccontando una storia" },
    { id: "r-animale", name: "Amico degli animali", knack: "si fa capire da bestie e insetti" },
    { id: "r-mappa", name: "Cartografo", knack: "non si perde, o almeno si perde meglio degli altri" },
    { id: "r-ombra", name: "Cacciatore d'ombre", knack: "segue le piste strane" },
    { id: "r-dado", name: "Portafortuna", knack: "quando il dado è indeciso, tira dalla vostra parte" },
    { id: "r-scala", name: "Arrampicatore", knack: "sale dove gli altri si fermano a guardare" },
    { id: "r-eco", name: "Ascoltatore di echi", knack: "sente quello che i muri ripetono" },
    { id: "r-chiave", name: "Chiavaio", knack: "prova ad aprire qualsiasi chiusura" },
    { id: "r-faro", name: "Portatore di lume", knack: "tiene accesa la lanterna e anche la speranza" },
    { id: "r-scudo", name: "Custode del gruppo", knack: "si mette in mezzo quando arriva il pericolo" }
  ];

  C.locations = [
    { id: "l-ponte", name: "un ponte di radici sopra un buco" },
    { id: "l-cucina", name: "una cucina abbandonata che cucina da sola" },
    { id: "l-pozzo", name: "un pozzo che ripete i nomi" },
    { id: "l-mercato", name: "un mercato dove si vendono le ore del giorno" },
    { id: "l-grotta", name: "una grotta di caramelle salate" },
    { id: "l-torre", name: "una torre fatta di cuscini impilati" },
    { id: "l-fiume", name: "un fiume di inchiostro" },
    { id: "l-stalla", name: "una stalla di cavalli di nebbia" },
    { id: "l-salone", name: "un salone pieno di specchi che mentono" },
    { id: "l-tetto", name: "dei tetti che si spostano da soli" },
    { id: "l-boschetto", name: "un boschetto che fa domande a voce alta" },
    { id: "l-mulino", name: "un mulino che macina i segreti" },
    { id: "l-spiaggia", name: "una spiaggia fatta di bottoni" },
    { id: "l-treno", name: "un vagone senza binari" },
    { id: "l-cimitero", name: "un giardino di statue impazienti" },
    { id: "l-biblioteca", name: "una sala di libri affamati" },
    { id: "l-cantina", name: "una cantina di risate in bottiglia" },
    { id: "l-piazza", name: "una piazza che cambia pavimento" },
    { id: "l-faro", name: "un faro in mezzo alla terra, senza mare" },
    { id: "l-miniera", name: "un cunicolo di luci perdute" },
    { id: "l-teatro", name: "un teatro con il palco vuoto" },
    { id: "l-orto", name: "un orto che semina da solo" },
    { id: "l-ponte2", name: "un ponte fatto di piatti e pentole" },
    { id: "l-nido", name: "un nido gigante dentro un camino" },
    { id: "l-scala", name: "una scala che salta i gradini" },
    { id: "l-lago", name: "uno specchio d'acqua che non riflette" },
    { id: "l-tenda", name: "una tenda di circo chiuso" },
    { id: "l-forno", name: "un forno che cuoce i piani" },
    { id: "l-vicolo", name: "un vicolo di ombre colorate" },
    { id: "l-albero", name: "un albero cavo pieno di posta" },
    { id: "l-molo", name: "un molo dove sono attraccate le nuvole" },
    { id: "l-cassa", name: "una stanza di cassette musicali" },
    { id: "l-ghiaccio", name: "una serra di ghiaccio dolce" },
    { id: "l-campane", name: "un campanile senza campane" },
    { id: "l-tappeto", name: "una sala con un tappeto vivo" },
    { id: "l-soffitta", name: "una soffitta di bauli a forma di chiocciola" },
    { id: "l-chiostro", name: "un chiostro fatto per le pause" },
    { id: "l-cava", name: "una cava di gessetti magici" },
    { id: "l-ponte3", name: "una passerella di fumo solido" },
    { id: "l-cuccia", name: "una cuccia reale dei cani di vento" },
    { id: "l-orologio", name: "una stanza dentro un orologio" },
    { id: "l-serra", name: "una serra di fiori pettegoli" },
    { id: "l-magazzino", name: "un magazzino di giorni in scatola" },
    { id: "l-crocevia", name: "un crocevia delle quattro merende" },
    { id: "l-cascata", name: "una cascata di coriandoli bagnati" },
    { id: "l-archivio", name: "un archivio di promesse" },
    { id: "l-cucina2", name: "una dispensa verticale, alta come una torre" },
    { id: "l-tunnel", name: "un tunnel di calzini" }
  ];

  function ch(spec) {
    return spec;
  }

  C.challenges = [
    ch({
      id: "c-ponte",
      kind: "danger",
      who: "one",
      title: "Il ponte stretto",
      player: "Siete su un ponte stretto. Sotto c'è un buco. Dovete passare dall'altra parte senza cadere.",
      master: "Siete a {location}.\n\nIl ponte è stretto, sotto c'è un buco nero, e {npc} vi grida di sbrigarvi: {villain} non è lontano.\n\nDovete arrivare all'altro lato. Un giocatore tira il dado per tutti.",
      secret: "Tira un giocatore. Se riesce, nella scena dopo siete in anticipo e il cattivo non vi ha visti. Se fallisce, perde un cuore e nella scena dopo arrivate in ritardo.",
      prompt: "Come passate il ponte?",
      choices: [
        { id: "run", label: "Attraversiamo di corsa, uno alla volta", target: 4, dmg: 1,
          ok: "Correte. Il ponte trema, ma tenete l'equilibrio. Dall'altra parte trovate un sentiero corto, nascosto tra le radici.",
          fail: "A metà ponte qualcuno scivola. Perde 1 cuore e il gruppo deve tornare indietro. L'unico altro modo è un sentiero lungo e faticoso.",
          okNext: "Avete preso la scorciatoia del ponte. Arrivate prima, e {villain} non sa ancora che siete qui.",
          failNext: "Il ponte vi ha fatto perdere un cuore e tanto tempo. Arrivate stanchi, e {villain} ha già capito che state arrivando." },
        { id: "build", label: "Costruiamo un passaggio con quello che abbiamo in tasca", target: 5, dmg: 1,
          ok: "Con corda, rami e un po' di inventiva fate un ponticello ridicolo ma solido. Passate tutti. Sotto, il buco resta a guardare.",
          fail: "Il ponticello crolla a metà. Chi tira resta appeso e perde 1 cuore. Dovete scendere e girare intorno, perdendo la via corta.",
          okNext: "Il ponticello vi ha fatti arrivare interi e in tempo. Il posto dopo è ancora calmo.",
          failNext: "Dopo la caduta arrivate dal lato lungo. Il posto dopo è già in allarme: qualcuno ha sentito il crollo." }
      ]
    }),
    ch({
      id: "c-indovinello",
      kind: "puzzle",
      who: "one",
      title: "La domanda del luogo",
      player: "Questo posto non vi fa passare se non rispondete a una domanda. Dovete trovare una risposta, o almeno tentare.",
      master: "Siete a {location}.\n\nUna voce chiede: «Che cosa si può spezzare senza toccarla?»\n\n{npc} sussurra che {villain} odia chi indovina. Il posto è capriccioso: conta il dado, non se la risposta è da enciclopedia. (Se i giocatori dicono «una promessa» o «il silenzio», fai comunque tirare, ma racconta che il posto ha apprezzato lo sforzo.)",
      secret: "La risposta «giusta» è una promessa o il silenzio. Il dado decide se il luogo si sposta. Successo: passaggio aperto. Fallimento: una piccola trappola e il giro lungo.",
      prompt: "Come rispondete?",
      choices: [
        { id: "think", label: "Pensiamo ad alta voce e diamo una risposta", target: 4, dmg: 1,
          ok: "Il luogo fa un «ahh» soddisfatto e si sposta. Davanti a voi c'è la strada dritta, con un segno lasciato da {villain}.",
          fail: "La risposta non piace. Scatta una piccola trappola: chi ha parlato perde 1 cuore. Il passaggio resta chiuso: dovete fare il giro.",
          okNext: "Il luogo vi ha aperti la strada dritta. Avete anche visto un segno del cattivo: sapete da che parte è andato.",
          failNext: "Il luogo si è offeso. Arrivate dal giro lungo, senza indizi, e con un cuore in meno." },
        { id: "trick", label: "Facciamo una domanda noi, per confonderlo", target: 5, dmg: 1,
          ok: "Il luogo si confonde e vi lascia passare «per rispetto». Non è la via più elegante, ma è aperta.",
          fail: "Il luogo si offende. Una raffica vi colpisce: chi tira perde 1 cuore. Poi il posto si chiude e dovete cercare un'altra uscita.",
          okNext: "Siete passati con una furbata. Il posto dopo non si aspetta ospiti così svegli.",
          failNext: "Dopo la raffica arrivate da un'uscita secondaria, scoperti e un po' malconci." }
      ]
    }),
    ch({
      id: "c-social",
      kind: "social",
      who: "one",
      title: "Chi blocca la strada",
      player: "Qualcuno vi blocca la strada e vuole qualcosa in cambio. Dovete convincerlo ad aiutarvi.",
      master: "Siete a {location}.\n\n{npc} vi blocca e chiede {treasure} in cambio di un favore. In realtà ha paura di {villain}.\n\nSe lo convinte, vi indica un passaggio nascosto. Se no, vi caccia e dovete continuare allo scoperto.",
      secret: "Successo: alleato e passaggio nascosto. Fallimento: 1 cuore e strada scoperta.",
      prompt: "Come lo convinte?",
      choices: [
        { id: "kind", label: "Raccontiamo la missione con calma, senza urlare", target: 4, dmg: 1,
          ok: "{npc} si scioglie. Vi crede. Vi indica un passaggio nascosto e vi dice dove {villain} tiene le sentinelle.",
          fail: "Non crede a una parola. Vi caccia con un colpo sfortunato: chi parlava perde 1 cuore. Dovete prendere la strada grande, in pieno vista.",
          okNext: "{npc} vi ha aperti un passaggio nascosto. Sapete anche dove stanno le sentinelle di {villain}.",
          failNext: "Siete stati cacciati. Arrivate dalla strada grande, in vista, senza aiuto." },
        { id: "trade", label: "Proponiamo uno scambio onesto (non il tesoro, un favore)", target: 5, dmg: 1,
          ok: "Lo scambio è fatto. Ottenete il passaggio e un consiglio su {villain}: di giorno è più distratto.",
          fail: "Lo scambio era una trappola. Chi tratta perde 1 cuore e per poco non perdete anche {treasure}. Dovete scappare allo scoperto.",
          okNext: "Lo scambio onesto vi ha dato un alleato. Il posto dopo è più facile: sapete quando il cattivo si distrae.",
          failNext: "Dopo la trappola non vi fidate più di nessuno. Arrivate guardinghi, e il tesoro è quasi caduto." }
      ]
    }),
    ch({
      id: "c-stealth",
      kind: "stealth",
      who: "two",
      title: "Passare senza farsi vedere",
      player: "Ci sono delle sentinelle. Dovete passare senza farvi sentire. Toccano a due di voi.",
      master: "Siete a {location}.\n\nCi sono le sentinelle di {villain}. {npc} fa da palo, ma trema.\n\nDue giocatori sono in azione. Tira il primo. Se fallisce, perde un cuore e le sentinelle danno l'allarme.",
      secret: "Due attori, un tiro del primo. Successo: passate puliti. Fallimento: allarme, 1 cuore, nella scena dopo il cattivo è avvisato.",
      prompt: "Quale piano usate?",
      choices: [
        { id: "shadow", label: "Strisciamo nell'ombra, in silenzio", target: 4, dmg: 1,
          ok: "Le sentinelle contano le nuvole. Passate. Nessuno ha visto niente. {npc} tira un sospiro.",
          fail: "Uno starnuto. Allarme. Chi tira perde 1 cuore e dovete scappare a gambe levate, senza nascondigli.",
          okNext: "Nessuno vi ha visti. Il posto dopo è ancora tranquillo: {villain} crede che non siate nei paraggi.",
          failNext: "L'allarme è partito. {villain} sa che ci siete. Il posto dopo è pieno di sentinelle." },
        { id: "disguise", label: "Ci travestiamo da gente del posto", target: 5, dmg: 1,
          ok: "Il travestimento regge. Qualcuno vi saluta persino. Passate di giorno, come se foste di casa.",
          fail: "Il travestimento cade a pezzi. Rissa lampo: chi tira perde 1 cuore. Scappate, e ora tutti sanno le vostre facce.",
          okNext: "Vi hanno presi per gente del posto. Nel posto dopo potete ancora fingere di essere di qui.",
          failNext: "Le vostre facce sono note. Nel posto dopo non potete più fingere: dovete nascondervi." }
      ]
    }),
    ch({
      id: "c-chase",
      kind: "chase",
      who: "two",
      title: "Qualcuno scappa con la roba",
      player: "Un servo del cattivo ha preso l'oggetto e scappa. Dovete acchiapparlo.",
      master: "Siete a {location}.\n\nUn servo di {villain} afferra {treasure} e scappa. {npc} urla: «Prendetelo!»\n\nDue di voi inseguono. Se ce la fate, il tesoro torna a voi. Se no, per ora lo perdete e dovete rincorrerlo più tardi.",
      secret: "Successo: tesoro recuperato. Fallimento: 1 cuore, tesoro perso per ora (resta in gioco, ma il cattivo è avanti).",
      prompt: "Come lo inseguite?",
      choices: [
        { id: "sprint", label: "Scatto a gambe levate, dritti dietro di lui", target: 4, dmg: 1,
          ok: "Lo acchiappate per il cappotto. {treasure} torna in tasca. Il servo scappa a mani vuote.",
          fail: "Inciampo collettivo. Chi tira perde 1 cuore. Il servo sparisce dietro un angolo con {treasure}. Dovrete riaverlo più avanti.",
          okNext: "{treasure} è di nuovo vostro. Arrivate al posto dopo con l'oggetto in tasca e un vantaggio.",
          failNext: "Il servo è scappato con {treasure}. Nel posto dopo lo vedete già in lontananza: {villain} è un passo avanti." },
        { id: "cut", label: "Tagliamo la strada dal vicolo di lato", target: 5, dmg: 1,
          ok: "Uscite da un vicolo ridicolo e lo beccate. {treasure} è vostro. Il servo resta a bocca aperta.",
          fail: "Il vicolo era cieco. Tonfo: chi tira perde 1 cuore. Il servo è già lontano con {treasure}.",
          okNext: "L'agguato ha funzionato. Avete {treasure} e il servo non ha fatto in tempo ad avvisare {villain}.",
          failNext: "Il vicolo cieco vi ha fatti perdere. {treasure} è avanti, con il servo, verso {villain}." }
      ]
    }),
    ch({
      id: "c-help",
      kind: "help",
      who: "one",
      title: "Qualcuno è in trappola",
      player: "Un amico è bloccato in una trappola. Dovete liberarlo senza farvi prendere anche voi.",
      master: "Siete a {location}.\n\n{npc} è bloccato in una trappola lasciata da {villain}. Chiede aiuto a voce bassa.\n\nSe lo liberate, vi aiuta dopo. Se la trappola scatta, chi aiuta perde cuori e {npc} resta spaventato.",
      secret: "Successo: alleato nella scena dopo. Fallimento: danno e l'NPC non aiuta.",
      prompt: "Come lo liberate?",
      choices: [
        { id: "care", label: "Disinneschiamo la trappola con calma", target: 4, dmg: 1,
          ok: "Click. {npc} è libero. Vi deve un favore e cammina con voi, indicando le trappole successive.",
          fail: "La trappola morde anche voi: chi aiuta perde 1 cuore. {npc} esce lo stesso, ma ha troppa paura per aiutarvi dopo.",
          okNext: "{npc} cammina con voi e vi avvisa delle trappole. Il posto dopo è meno pericoloso.",
          failNext: "{npc} è libero ma terrorizzato: non parla. Nel posto dopo siete da soli a cercare le trappole." },
        { id: "force", label: "Tiriamo con tutta la forza", target: 5, dmg: 2,
          ok: "Spaccate la trappola. Fate rumore, ma {npc} è salvo e vi considera eroi. Vi seguirà.",
          fail: "Cede di colpo: lo strattone costa 2 cuori a chi tira. {npc} è fuori, ma il rumore ha chiamato attenzione.",
          okNext: "Siete eroi per {npc}. Vi segue. Nel posto dopo avete un aiuto in più, anche se qualcuno potrebbe avervi sentiti.",
          failNext: "Il rumore dello strattone è arrivato lontano. {villain} ha alzato la testa. Il posto dopo non è più vuoto." }
      ]
    }),
    ch({
      id: "c-moral",
      kind: "moral",
      who: "one",
      title: "Non si può salvare tutto insieme",
      player: "Dovete scegliere: l'oggetto che cade, o l'amico che sta per essere scoperto. Una cosa sola, adesso.",
      master: "Siete a {location}.\n\nNello stesso momento: {treasure} sta per cadere in un buco, e {npc} sta per essere visto da un servo di {villain}.\n\nNon potete fare tutte e due le cose. Chi tira sceglie. L'altra cosa non è persa per sempre, ma per ora va in un'altra direzione.",
      secret: "Due strade vere. Successo: salvate quella che avete scelto e l'altra si recupera dopo. Fallimento: 1 cuore e perdete (per ora) tutte e due.",
      prompt: "Cosa salvate adesso?",
      choices: [
        { id: "item", label: "Salviamo l'oggetto, poi corriamo dall'amico", target: 4, dmg: 1,
          ok: "Afferrate {treasure}. {npc} ce la fa per un pelo da solo e vi raggiunge dopo, un po' offeso ma vivo.",
          fail: "Perdete la presa: {treasure} cade nel buco e {npc} viene scoperto. Chi tira perde 1 cuore. Dovrete recuperarli più avanti, da {villain}.",
          okNext: "Avete {treasure} con voi. {npc} vi raggiunge più tardi. Il posto dopo è vostro da attraversare.",
          failNext: "Non avete né l'oggetto né l'amico. Tutti e due sono finiti verso {villain}. Il posto dopo è vuoto e cattivo." },
        { id: "friend", label: "Copriamo l'amico: l'oggetto può aspettare", target: 4, dmg: 1,
          ok: "{npc} è salvo. {treasure} fa «cling» in un cespuglio: lo ritroverete tra poco, ma non adesso.",
          fail: "Vi scoprono mentre coprite {npc}. Scontro breve: chi tira perde 1 cuore. {treasure} sparisce con un servo.",
          okNext: "{npc} è con voi, grato. {treasure} è nel cespuglio: nel posto dopo potete ancora prenderlo.",
          failNext: "Siete stati scoperti. {treasure} è in mano a un servo. {npc} è salvo, ma il cattivo sa dove siete." }
      ]
    }),
    ch({
      id: "c-explore",
      kind: "explore",
      who: "one",
      title: "Il dettaglio nascosto",
      player: "Questo posto sembra vuoto. Troppo vuoto. Dovete cercare un indizio senza far scattare una trappola.",
      master: "Siete a {location}.\n\nSembra vuoto. {npc} dice che {villain} lascia sempre una traccia, se sapete dove guardare.\n\nSe trovate l'indizio, sapete dov'è il covo. Se scatta la trappola, perdete un cuore e restate senza pista.",
      secret: "Successo: indizio sul covo. Fallimento: trappola, niente pista.",
      prompt: "Dove cercate?",
      choices: [
        { id: "high", label: "Guardiamo in alto, sempre in alto", target: 4, dmg: 1,
          ok: "In alto c'è un segno: una freccia storta verso il covo di {villain}. Ora sapete da che parte andare.",
          fail: "Vi cade addosso qualcosa di pesante. Chi guarda in alto perde 1 cuore. L'indizio, se c'era, è finito in pezzi.",
          okNext: "Avete la direzione del covo. Il posto dopo è sulla strada giusta.",
          failNext: "Senza indizio prendete la prima strada che capita. Potrebbe essere quella lunga." },
        { id: "low", label: "Frughiamo in basso, tra le fessure", target: 5, dmg: 1,
          ok: "Trovate un passaggio da topi, basso e perfetto. Porta vicino al covo, senza sentinelle.",
          fail: "Qualcosa vi morde un dito. Chi fruga perde 1 cuore. Il passaggio da topi si chiude.",
          okNext: "Il passaggio da topi vi porta sotto il posto dopo, senza incontrare nessuno.",
          failNext: "Il passaggio è chiuso. Dovete camminare sopra, dove tutti vi possono vedere." }
      ]
    }),
    ch({
      id: "c-storm",
      kind: "danger",
      who: "two",
      title: "La bufera",
      player: "È arrivata una bufera voluta dal cattivo. Dovete resistere o farla passare.",
      master: "Siete a {location}.\n\nUna bufera voluta da {villain} si abbatte sul posto. {npc} cerca un riparo che forse non c'è.\n\nDue di voi tengono il gruppo. Tira il primo. Se fallisce, perde un cuore e la bufera vi spinge nella direzione sbagliata.",
      secret: "Successo: la bufera passa e voi restate sulla strada. Fallimento: 1 cuore e venite spinti fuori strada.",
      prompt: "Come resistete?",
      choices: [
        { id: "shelter", label: "Ci accovacciamo e aspettiamo che passi il peggio", target: 4, dmg: 1,
          ok: "La bufera vi lecca e se ne va, annoiata. Siete sulla strada giusta, solo un po' bagnati.",
          fail: "Vi prende in pieno. Chi tira perde 1 cuore. Il vento vi spinge in un sentiero che non volevate.",
          okNext: "La bufera è passata. Siete ancora sulla strada giusta, solo bagnati.",
          failNext: "Il vento vi ha spinti fuori strada. Il posto dopo non è quello che cercavate: è più esposto." },
        { id: "sing", label: "Cantiamo per calmare il posto", target: 5, dmg: 1,
          ok: "Il luogo si intenerisce. La bufera fa un inchino e se ne va. {npc} applaude.",
          fail: "Siete stonati. La bufera si offende: chi canta perde 1 cuore e venite sballottati lontano.",
          okNext: "Il posto vi è amico, dopo il canto. Anche il luogo dopo vi tratta meglio.",
          failNext: "La bufera offesa vi ha sballottati lontano. Arrivate da un lato sbagliato e senza fiato." }
      ]
    }),
    ch({
      id: "c-lock",
      kind: "puzzle",
      who: "one",
      title: "La porta capricciosa",
      player: "Una porta non si apre. Vuole un pedaggio strano. Dovete convincerla o sbloccarla.",
      master: "Siete a {location}.\n\nUna porta chiede un pedaggio strano. {npc} ha già fallito tre volte. Dietro c'è un pezzo della missione contro {villain}.\n\nIl dado decide se la porta accetta. Se dice di no, morde e dovete cercare un'altra entrata.",
      secret: "Successo: entrate di qui, vicino alla missione. Fallimento: 1 cuore e ingresso secondario, più lungo.",
      prompt: "Come aprite la porta?",
      choices: [
        { id: "key", label: "Proviamo tutte le chiavi, anche quelle inventate", target: 4, dmg: 1,
          ok: "Una chiave finta diventa vera per un secondo. Basta. La porta si apre sulla stanza giusta.",
          fail: "La porta morde le dita: chi prova perde 1 cuore. Resta chiusa. Dovete girare fino a una finestra scomoda.",
          okNext: "Siete entrati dalla porta giusta. Il posto dopo è la stanza che vi serviva.",
          failNext: "Siete entrati da una finestra scomoda, in ritardo. Il posto dopo è già stato messo in disordine da {villain}." },
        { id: "ask", label: "Chiediamo scusa alla porta e spieghiamo perché ci serve", target: 5, dmg: 1,
          ok: "La porta è di buon umore. Si apre sbadigliando. Vi fa anche un inchino, di legno.",
          fail: "Non accetta scuse deboli. Sbatte: chi parlava perde 1 cuore. Dovete scavalcare da un lato.",
          okNext: "La porta vi ha fatti amici. Anche le porte dopo potrebbero ascoltarvi.",
          failNext: "La porta ha sbattuto. Le altre chiusure del posto dopo sono ancora più ostili." }
      ]
    }),
    ch({
      id: "c-climb",
      kind: "danger",
      who: "one",
      title: "La salita",
      player: "Per proseguire bisogna salire. Se cadete, fa male. Se arrivate in cima, siete sulla strada giusta.",
      master: "Siete a {location}.\n\nPer proseguire bisogna salire. Sotto, {npc} tiene (forse) una corda. Sopra, c'è odore di {villain}.\n\nUn giocatore sale per primo. Se cade, perde cuori e il gruppo deve trovare un'altra salita, più lunga.",
      secret: "Successo: cima e via breve. Fallimento: caduta e via lunga.",
      prompt: "Come salite?",
      choices: [
        { id: "slow", label: "Salita lenta, presa per presa", target: 4, dmg: 1,
          ok: "In cima. Le ginocchia protestano, ma siete lì. Davanti c'è il sentiero corto verso {villain}.",
          fail: "Molla una presa. Caduta: chi sale perde 1 cuore. {npc} vi aiuta a terra, e poi dovete cercare una scala lunga.",
          okNext: "Dalla cima vedete tutto. Il posto dopo è sotto di voi, e sapete già com'è fatto.",
          failNext: "Dopo la caduta prendete la scala di servizio. Arrivate dal basso, senza vista sul posto dopo." },
        { id: "leap", label: "Salti arditi, come nei racconti", target: 6, dmg: 2,
          ok: "Un salto da racconto. {npc} applaude. Siete in cima in un attimo, e {villain} non ha sentito passi.",
          fail: "I racconti mentivano. Tonfo: chi salta perde 2 cuori. Dovete strisciare su per un canaletto umido.",
          okNext: "Il salto silenzioso vi ha messi in cima senza rumore. {villain} non alza la testa.",
          failNext: "Il tonfo si è sentito lontano. Arrivate dal canaletto, e qualcuno ha già sentito il rumore." }
      ]
    }),
    ch({
      id: "c-cook",
      kind: "puzzle",
      who: "one",
      title: "Il pentolone giudice",
      player: "Un pentolone esige un piatto. Se gli piace, vi apre la strada. Se no, schizza.",
      master: "Siete a {location}.\n\nUn pentolone esige un ingrediente. {npc} propone di usare {treasure} come mestolo. {villain} ha già tentato di bruciare tutto.\n\nIl pentolone è il giudice: il dado decide se il piatto va. Se no, scotta e la cucina resta chiusa.",
      secret: "Successo: la cucina apre un passaggio. Fallimento: 1 cuore e uscita dalla dispensa, più lunga.",
      prompt: "Cosa cucinate?",
      choices: [
        { id: "careful", label: "Seguiamo la ricetta alla lettera", target: 4, dmg: 1,
          ok: "Profumo di vittoria. Il pentolone vi benedice e mostra una botola sotto il focolare.",
          fail: "Troppo sale magico. Schizzo bollente: chi cucina perde 1 cuore. La botola resta chiusa: si esce dalla dispensa.",
          okNext: "La botola sotto il focolare vi porta dritti al posto dopo, caldi e nascosti.",
          failNext: "Uscite dalla dispensa, bruciati e visibili. Il posto dopo vi vede arrivare." },
        { id: "improv", label: "Inventiamo, con coraggio e un po' di caos", target: 5, dmg: 1,
          ok: "Nasce un piatto impossibile. Il pentolone ride e apre la porta di servizio.",
          fail: "Il caos è troppo. Esplosione di brodo: chi mescola perde 1 cuore. Dovete uscire dalla finestra della cucina.",
          okNext: "La porta di servizio è vostra. Arrivate al posto dopo dal retro, inosservati.",
          failNext: "La finestra vi ha fatti cadere fuori. Arrivate sporchi di brodo, e si vede da lontano." }
      ]
    }),
    ch({
      id: "c-dark",
      kind: "stealth",
      who: "one",
      title: "Il buio che ascolta",
      player: "Qui il buio sente i passi. Dovete avanzare senza farvi sentire.",
      master: "Siete a {location}.\n\nIl buio ascolta i passi. {npc} vi prende la mano. {villain} ha orecchie anche qui.\n\nSe passate in silenzio, uscite vicini alla meta. Se il buio vi sente, morde un cuore e vi spinge in un corridoio più lungo.",
      secret: "Successo: via breve nel buio. Fallimento: 1 cuore e corridoio lungo.",
      prompt: "Come avanzate?",
      choices: [
        { id: "silent", label: "Passi di velluto, niente parole", target: 4, dmg: 1,
          ok: "Il buio vi ignora. Uscite da una fessura proprio vicino a dove serve.",
          fail: "Un sassolino traditore. Il buio morde: chi camminava perde 1 cuore. Vi spinge in un corridoio che gira troppo.",
          okNext: "Siete usciti dal buio nel punto giusto. Il posto dopo è a due passi.",
          failNext: "Il corridoio lungo vi ha fatti girare. Arrivate al posto dopo dal lato opposto, disorientati." },
        { id: "light", label: "Accendiamo un lume piccolo piccolo", target: 5, dmg: 1,
          ok: "La luce è una cortesia. Il buio accetta e vi fa strada da solo.",
          fail: "Troppa luce. Il buio si adombra e vi acceca un attimo: chi tiene il lume perde 1 cuore. Poi vi caccia fuori dalla parte sbagliata.",
          okNext: "Il buio vi ha fatti da guida. Sapete già com'è fatto il posto dopo.",
          failNext: "Siete stati cacciati dalla parte sbagliata. Il posto dopo vi gira le spalle." }
      ]
    }),
    ch({
      id: "c-market",
      kind: "social",
      who: "two",
      title: "Una voce in vendita",
      player: "Al mercato si vende una voce che sa dove il cattivo nasconde le cose. Dovete ottenerla.",
      master: "Siete a {location}.\n\nSi vende una voce: sa dove {villain} nasconde le cose. {npc} fa da interprete. Il prezzo non è denaro: è un dado.\n\nDue di voi contrattano. Se la voce è vostra, avete un indizio. Se no, vi derubano di un cuore e restate senza notizie.",
      secret: "Successo: indizio sul nascondiglio. Fallimento: 1 cuore, niente indizio.",
      prompt: "Come contrattate?",
      choices: [
        { id: "fair", label: "Paghiamo con un racconto vero", target: 4, dmg: 1,
          ok: "La voce è vostra. Vi dice dov'è il nascondiglio di {villain}: dietro la terza porta a sinistra.",
          fail: "Il racconto non convince. Vi derubano di 1 cuore (fa davvero male) e la voce se ne va da un'altra parte.",
          okNext: "Sapete della terza porta a sinistra. Nel posto dopo andate dritti lì.",
          failNext: "Senza la voce dovete indovinare. Nel posto dopo aprite la prima porta che capita." },
        { id: "bluff", label: "Bluffiamo di essere ispettori di {villain}", target: 6, dmg: 1,
          ok: "Funziona, per poco. Scappate con l'informazione: il nascondiglio è sotto una cassa.",
          fail: "Bluff orribile. Scandalo: chi ha parlato perde 1 cuore e il mercato vi caccia. Niente indizio.",
          okNext: "Avete l'info della cassa. Nel posto dopo sapete cosa sollevare.",
          failNext: "Il mercato vi ha cacciati. Arrivate al posto dopo senza mappa e con la faccia nota." }
      ]
    }),
    ch({
      id: "c-bridge-riddle",
      kind: "puzzle",
      who: "one",
      title: "Il guardiano",
      player: "Un guardiano vieta il passo. Non è cattivo: lavora per sbaglio per il cattivo. Dovete passare.",
      master: "Siete a {location}.\n\nUn guardiano vieta il passo. Non è cattivo: è impiegato di {villain} per sbaglio. {npc} conosce una scappatoia.\n\nSe lo convinte o lo aggirate, passate. Se vi becca, spintone magico e via secondaria.",
      secret: "Successo: passo principale. Fallimento: 1 cuore e via secondaria.",
      prompt: "Che strategia usate?",
      choices: [
        { id: "paper", label: "Tiriamo fuori un permesso inventato benissimo", target: 5, dmg: 1,
          ok: "Il permesso diventa vero per burocrazia magica. Il guardiano vi fa un saluto e apre.",
          fail: "Manca un bollo. Multa in cuori: chi mostra la carta perde 1 cuore. Vi mandano alla coda lunga.",
          okNext: "Il permesso vale ancora. Nel posto dopo i guardiani vi fanno passare.",
          failNext: "Siete in coda lunga, senza permesso. Nel posto dopo i guardiani sono sospettosi." },
        { id: "side", label: "Passiamo di lato mentre {npc} distrae", target: 4, dmg: 1,
          ok: "Classico e funziona. Siete oltre il posto di blocco, sulla strada principale.",
          fail: "Vi beccano. Spintone magico: chi scivolava perde 1 cuore. Vi spingono su un sentiero laterale.",
          okNext: "Siete sulla strada principale, oltre il blocco.",
          failNext: "Il sentiero laterale è fangoso e lento. Arrivate dopo, sporchi." }
      ]
    }),
    ch({
      id: "c-ice",
      kind: "danger",
      who: "one",
      title: "Il suolo scivoloso",
      player: "Il suolo è scivoloso come una bugia. Dovete attraversare senza cadere di sotto.",
      master: "Siete a {location}.\n\nÈ scivoloso. {npc} ha già fatto una piroetta non richiesta. {villain} ama chi cade.\n\nSe attraversate, siete dall'altra parte. Se cadete, perdete un cuore e dovete strisciare dal bordo, più lento.",
      secret: "Successo: attraversata. Fallimento: 1 cuore e bordo lento.",
      prompt: "Come lo attraversate?",
      choices: [
        { id: "slide", label: "Ci lasciamo scivolare di proposito, come in slitta", target: 4, dmg: 1,
          ok: "Una slitta umana. Arrivate ridendo, dall'altra parte, in tempo.",
          fail: "La slitta finisce contro un muro. Chi guida perde 1 cuore. Poi dovete strisciare dal bordo.",
          okNext: "La slitta vi ha fatti arrivare in tempo. Il posto dopo è ancora vuoto.",
          failNext: "Dopo il muro strisciate dal bordo. Arrivate tardi: il posto dopo è già occupato." },
        { id: "grip", label: "Ci attacchiamo a ogni asperità, lenti e sicuri", target: 5, dmg: 1,
          ok: "Lenti e salvi. Dall'altra parte trovate anche un appiglio utile per dopo.",
          fail: "Molla tutto. Caduta: chi teneva perde 1 cuore. L'unica via è il bordo lungo.",
          okNext: "Avete un appiglio in più. Nel posto dopo sapete dove mettervi le mani.",
          failNext: "Senza appigli arrivate dal bordo lungo, con le mani doloranti." }
      ]
    }),
    ch({
      id: "c-song",
      kind: "social",
      who: "one",
      title: "Il canto che apre",
      player: "Questo posto si apre solo con un canto. Il cattivo ha vietato la musica. Dovete cantare lo stesso.",
      master: "Siete a {location}.\n\nIl posto si apre solo con un canto. {npc} è stonato. {villain} ha vietato la musica.\n\nNon conta l'orecchio: conta il coraggio (il dado). Se il canto piace, la via si apre. Se no, il posto vi spinge via.",
      secret: "Successo: via aperta. Fallimento: 1 cuore e spinta verso un'altra strada.",
      prompt: "Chi canta, e come?",
      choices: [
        { id: "solo", label: "Un assolo coraggioso", target: 4, dmg: 1,
          ok: "Il luogo fa bis e si apre. La strada dritta è vostra.",
          fail: "Fischi magici. Chi canta perde 1 cuore di imbarazzo vero. Il posto vi spinge su una rampa laterale.",
          okNext: "La strada dritta, aperta dal canto, vi porta al posto dopo senza ostacoli.",
          failNext: "La rampa laterale è stretta. Arrivate al posto dopo di lato, non di fronte." },
        { id: "choir", label: "Un coro improvvisato, tutti insieme", target: 5, dmg: 1,
          ok: "Stonati insieme, quindi perfetti. Il divieto di {villain} si spezza un attimo e passate.",
          fail: "Caos sonoro. Il luogo vi spinge via: chi ha dato il la perde 1 cuore. Uscita di servizio.",
          okNext: "Il divieto di musica è crepato. Nel posto dopo potete ancora fare rumore senza paura.",
          failNext: "Dopo la spinta uscite di servizio. Nel posto dopo il divieto di musica è ancora saldo." }
      ]
    }),
    ch({
      id: "c-trap",
      kind: "danger",
      who: "one",
      title: "Il pavimento bugiardo",
      player: "Le mattonelle mentono: alcune tengono, altre no. Dovete attraversare.",
      master: "Siete a {location}.\n\nIl pavimento ha mattonelle che mentono. {npc} dice: «Mai quelle a pois… o sì, aspetta.» Le ha fatte {villain}.\n\nSe indovinate il passo, siete oltre. Se no, scossa e dovete camminare sul bordo.",
      secret: "Le pois sono un bluff: conta il dado. Successo: via centrale. Fallimento: danno e bordo.",
      prompt: "Come avanzate?",
      choices: [
        { id: "test", label: "Proviamo ogni passo con un rametto", target: 4, dmg: 1,
          ok: "Lenti. Vivi. Il pavimento si annoia e vi lascia la via di mezzo.",
          fail: "Una mattonella vince. Scossa: chi prova perde 1 cuore. Dovete fare tutto il bordo.",
          okNext: "La via di mezzo è vostra. Il posto dopo ha lo stesso pavimento, e ora lo conoscete.",
          failNext: "Dal bordo arrivate tardi. Nel posto dopo il pavimento è ancora un mistero." },
        { id: "dash", label: "Una corsa dritta, occhi a metà chiusi", target: 5, dmg: 2,
          ok: "Sorprendete il pavimento. Non fa in tempo. Siete oltre, di slancio.",
          fail: "Fa in tempo. Chi corre perde 2 cuori. Poi strisciate sul bordo, lenti.",
          okNext: "Lo slancio vi ha messi oltre. Il posto dopo non vi aspetta così veloci.",
          failNext: "Dopo la scossa siete lenti e doloranti. Il posto dopo vi vede arrivare da lontano." }
      ]
    }),
    ch({
      id: "c-animal",
      kind: "social",
      who: "one",
      title: "La bestia di confine",
      player: "Una bestia blocca il passaggio. Non è del cattivo, è solo irritata. Dovete farvi accettare.",
      master: "Siete a {location}.\n\nUna bestia custode blocca il passo. Non è di {villain}, ma è irritata. {npc} parla un po' la sua lingua.\n\nNiente violenza: è un gioco in famiglia. Se vi accetta, vi scorta. Se no, un morso d'orgoglio e passate da soli, peggio.",
      secret: "Successo: la bestia vi scorta. Fallimento: 1 cuore e niente scorta.",
      prompt: "Come vi presentate?",
      choices: [
        { id: "food", label: "Offriamo cibo (anche immaginario, ma convinto)", target: 4, dmg: 1,
          ok: "La bestia accetta e vi scorta un tratto. Le altre creature del posto dopo vi lasceranno stare.",
          fail: "Non era cibo, per lei. Morso d'orgoglio: chi offre perde 1 cuore. La bestia se ne va e vi lascia soli.",
          okNext: "La scorta della bestia vale ancora. Nel posto dopo gli animali non vi attaccano.",
          failNext: "Senza scorta, nel posto dopo le creature sono ostili e dovete fare attenzione." },
        { id: "bow", label: "Facciamo un inchino lunghissimo", target: 5, dmg: 1,
          ok: "Rispetto ottenuto. Passate. La bestia vi indica anche la via più sicura.",
          fail: "Inchino troppo corto. Offesa: chi si è piegato perde 1 cuore. La via sicura resta ignota.",
          okNext: "Conoscete la via più sicura. Il posto dopo è quello che la bestia vi ha indicato.",
          failNext: "Senza indicazione prendete una via a caso. Potrebbe essere quella della bestia arrabbiata." }
      ]
    }),
    ch({
      id: "c-repair",
      kind: "puzzle",
      who: "two",
      title: "L'aggeggio rotto",
      player: "Un meccanismo dovrebbe aiutarvi, ma è rotto. Il cattivo l'ha sabotato. Dovete ripararlo.",
      master: "Siete a {location}.\n\nUn meccanismo dovrebbe aiutarvi. È rotto. {npc} ha due attrezzi e tre opinioni. L'ha sabotato {villain}.\n\nDue teste, un tiro. Se riparte, vi porta avanti. Se no, scossa e andate a piedi.",
      secret: "Successo: il meccanismo vi porta. Fallimento: 1 cuore e a piedi.",
      prompt: "Come lo riparate?",
      choices: [
        { id: "manual", label: "Seguiamo le istruzioni scritte storte", target: 4, dmg: 1,
          ok: "Click-clack. Funziona, più o meno. Vi porta al posto dopo senza camminare.",
          fail: "Istruzioni capovolte. Scossa: chi legge perde 1 cuore. L'aggeggio resta morto: a piedi.",
          okNext: "Il meccanismo vi ha scarrozzati. Arrivate interi, senza aver camminato.",
          failNext: "A piedi, dopo la scossa, arrivate stanchi. Il posto dopo è più lontano di quanto sembrava." },
        { id: "kick", label: "Un colpo secco nel punto giusto (speriamo)", target: 6, dmg: 1,
          ok: "Il colpo della leggenda. Parte. Vi spara dolcemente in avanti.",
          fail: "Punto sbagliato. Il meccanismo morde: chi ha dato il colpo perde 1 cuore. Poi si spegne per sempre.",
          okNext: "Siete arrivati di slancio, grazie al colpo. Il posto dopo non vi ha sentiti arrivare.",
          failNext: "L'aggeggio è morto. Camminate. {villain} ha tutto il tempo di prepararvi il benvenuto." }
      ]
    }),
    ch({
      id: "c-memory",
      kind: "puzzle",
      who: "one",
      title: "I ricordi che mentono",
      player: "Questo posto mostra ricordi che non sono vostri. Alcuni sono bugie del cattivo. Dovete trovare quello vero.",
      master: "Siete a {location}.\n\nIl posto mostra ricordi che non sono vostri. {npc} dice di non credere a tutto. {villain} nasconde bugie in mezzo.\n\nSe trovate il ricordo vero, sapete qualcosa sul covo. Se ingoiate una bugia, fa male e restate senza pista.",
      secret: "Successo: verità sul covo. Fallimento: 1 cuore e niente verità.",
      prompt: "Cosa fate?",
      choices: [
        { id: "focus", label: "Cerchiamo il ricordo che ha un odore vero", target: 4, dmg: 1,
          ok: "Trovate una verità utile: il covo di {villain} ha una porta dietro un tendaggio rosso.",
          fail: "Ingoiate una bugia. Fa male: chi ha scelto perde 1 cuore. La pista è falsa.",
          okNext: "Cercate il tendaggio rosso. Nel posto dopo sapete cosa aprire.",
          failNext: "La pista falsa vi porta dalla parte opposta. Nel posto dopo non c'è nessun tendaggio." },
        { id: "close", label: "Chiudiamo gli occhi e usciamo a tentoni", target: 5, dmg: 1,
          ok: "Non vi fate fregare. Uscita pulita, sulla strada vera, anche senza l'indizio extra.",
          fail: "Inciampate in un ricordo tagliente: chi cammina a occhi chiusi perde 1 cuore. Uscite storti.",
          okNext: "Uscita pulita. Siete sulla strada vera, senza bugie in testa.",
          failNext: "Uscite storti, con una bugia ancora attaccata. Nel posto dopo vi fidate della cosa sbagliata." }
      ]
    }),
    ch({
      id: "c-crowd",
      kind: "social",
      who: "one",
      title: "La folla convinta del contrario",
      player: "Una folla crede che siate amici del cattivo. Dovete farvi ascoltare o andarne via in tempo.",
      master: "Siete a {location}.\n\nUna folla è convinta che siate amici di {villain}. {npc} tenta un discorso.\n\nSe li convinte, vi aiutano. Se no, pomodori (magici) e dovete scappare per i vicoli.",
      secret: "Successo: la folla aiuta. Fallimento: 1 cuore e fuga nei vicoli.",
      prompt: "Come gestite la folla?",
      choices: [
        { id: "speech", label: "Un discorso dal cuore, chiaro e lento", target: 5, dmg: 1,
          ok: "La folla si scioglie. Qualcuno vi applaude e vi indica la via breve verso {villain}.",
          fail: "Pomodori magici. Chi parla perde 1 cuore. Dovete scappare per i vicoli, senza indicazioni.",
          okNext: "La folla vi ha indicati la via breve. Il posto dopo è quello giusto.",
          failNext: "I vicoli vi hanno fatti girare. Arrivate al posto dopo da un culo di sacco." },
        { id: "exit", label: "Una scusa brillante e una retrata dignitosa", target: 4, dmg: 1,
          ok: "Uscita elegante. Nessun pomodoro. Restate anonimi e potete ancora muovervi in città.",
          fail: "Inciampo pubblico. Ahia: chi indietreggia perde 1 cuore. La folla vi segue per un tratto.",
          okNext: "Siete ancora anonimi. Nel posto dopo nessuno vi ferma.",
          failNext: "La folla vi ha visti inciampare. Nel posto dopo qualcuno vi riconosce e chiacchiera." }
      ]
    }),
    ch({
      id: "c-water",
      kind: "danger",
      who: "two",
      title: "L'attraversata bagnata",
      player: "C'è da attraversare un tratto d'acqua (o brodo, o inchiostro). Qualcuno non nuota. Dovete passare.",
      master: "Siete a {location}.\n\nC'è da attraversare. {npc} non nuota. {villain} ha messo correnti storte.\n\nDue persone: una guida, una aiuta. Se la zattera (o il nuoto) regge, siete oltre. Se no, un cuore bagnato e il giro sulle sponde.",
      secret: "Successo: oltre l'acqua. Fallimento: 1 cuore e sponda lunga.",
      prompt: "Come attraversate?",
      choices: [
        { id: "float", label: "Costruiamo una zattera lampo", target: 4, dmg: 1,
          ok: "Galleggia. È brutta. È vostra. Sbarcate dove volevate.",
          fail: "Affonda a metà. Chi stava sopra perde 1 cuore. Dovete tornare e girare sulle sponde.",
          okNext: "Sbarcati nel punto giusto. Il posto dopo è quello sulla riva che volevate.",
          failNext: "Girate sulle sponde. Arrivate all'altra riva tardi, e non è quella che volevate." },
        { id: "swim", label: "Nuoto deciso, corda tra i denti", target: 5, dmg: 1,
          ok: "Arrivate grondanti e dalla parte giusta. La corrente storta non vi ha presi.",
          fail: "La corrente storta strattona: chi nuota perde 1 cuore. Vi scarica a valle, fuori strada.",
          okNext: "Siete sulla riva giusta, grondanti ma nel posto giusto.",
          failNext: "A valle. Il posto dopo è quello sbagliato, e dovete risalire." }
      ]
    }),
    ch({
      id: "c-time",
      kind: "puzzle",
      who: "one",
      title: "I minuti che scappano",
      player: "I minuti scappano verso il cattivo. Se ne acchiappate uno, avete un respiro in più. Se no, il tempo vi è nemico.",
      master: "Siete a {location}.\n\nI minuti scappano verso {villain}. {npc} tenta di acchiapparne uno per la coda.\n\nSe ne tenete uno, nella scena dopo avete più calma. Se vi morde, perdete un cuore e arrivate in ritardo.",
      secret: "Successo: vantaggio di tempo dopo. Fallimento: 1 cuore e ritardo.",
      prompt: "Come fermate (un po') il tempo?",
      choices: [
        { id: "catch", label: "Acchiappiamo un minuto a mani nude", target: 5, dmg: 1,
          ok: "Ne tenete uno. Vi dà un respiro in più: nella scena dopo potete guardarvi intorno prima di agire.",
          fail: "Vi morde: i minuti hanno denti. Chi afferra perde 1 cuore. Gli altri minuti scappano tutti da {villain}.",
          okNext: "Avete un minuto in tasca. Nel posto dopo potete guardarvi intorno prima che succeda qualcosa.",
          failNext: "I minuti sono tutti da {villain}. Nel posto dopo tutto succede troppo in fretta." },
        { id: "wait", label: "Restiamo fermi finché i minuti si annoiano", target: 4, dmg: 1,
          ok: "Funziona. I minuti vanno a infastidire altri. Voi ripartite in orario.",
          fail: "Vi annoiate voi, e pagate: chi aspetta perde 1 cuore. Poi siete in ritardo lo stesso.",
          okNext: "Ripartite in orario. Il posto dopo non è ancora scattato.",
          failNext: "In ritardo. Nel posto dopo la trappola è già armata." }
      ]
    }),
    ch({
      id: "c-maze",
      kind: "explore",
      who: "one",
      title: "Il labirinto che cambia",
      player: "È un labirinto che cambia se vi pentite. Dovete scegliere una regola e tenerla.",
      master: "Siete a {location}.\n\nÈ un labirinto che cambia se vi pentite. {npc} consiglia di scegliere e basta. {villain} ama chi torna indietro.\n\nSe tenete la regola, uscite. Se la rompete, un cuore e uscite dal lato sbagliato.",
      secret: "Successo: uscita giusta. Fallimento: 1 cuore e uscita sbagliata.",
      prompt: "Come lo affrontate?",
      choices: [
        { id: "left", label: "Sempre a sinistra, come un giuramento", target: 4, dmg: 1,
          ok: "Il labirinto rispetta i giuramenti, anche quelli un po' stupidi. Uscita sulla strada della missione.",
          fail: "Un vicolo vi fa rompere il giuramento. Tonfo: chi decideva perde 1 cuore. Uscite dal lato del cattivo.",
          okNext: "Siete sulla strada della missione. Il posto dopo è quello che cercavate.",
          failNext: "Siete usciti dal lato di {villain}. Il posto dopo è più vicino a lui, e più pericoloso." },
        { id: "mark", label: "Lasciamo segni e ci fidiamo dei segni", target: 5, dmg: 1,
          ok: "I segni restano. Uscita. Avete anche una traccia per tornare indietro dopo.",
          fail: "I segni camminano via. Smarriti: chi segnava perde 1 cuore. Uscite dove capita.",
          okNext: "Avete i segni per tornare. Nel posto dopo non vi perdete.",
          failNext: "Senza segni, nel posto dopo è facile perdersi di nuovo." }
      ]
    }),
    ch({
      id: "c-gift",
      kind: "moral",
      who: "one",
      title: "Il regalo troppo bello",
      player: "C'è un dono che sembra l'oggetto che cercate. Il cattivo regala spesso. Troppo spesso.",
      master: "Siete a {location}.\n\nC'è un dono: sembra {treasure}. {npc} dice che {villain} regala spesso. Troppo spesso.\n\nSe lo controllate bene e va liscio, è vostro. Se è una trappola, fa male e l'oggetto vero è altrove. Se lo lasciate, il dono può indicarvi la strada — o inseguirvi.",
      secret: "Due strade vere. Successo: oggetto vero o indicazione. Fallimento: 1 cuore e trappola/inseguimento.",
      prompt: "Che fate del dono?",
      choices: [
        { id: "take", label: "Lo prendiamo, ma lo controlliamo bene prima", target: 5, dmg: 1,
          ok: "Era quasi una trappola. L'avete disinnescata. Ora {treasure} (o un pezzo vero) è vostro, onesto.",
          fail: "Trappola. Chi tocca perde 1 cuore. L'oggetto vero non è questo: è già da {villain}.",
          okNext: "Avete l'oggetto onesto con voi. Nel posto dopo vi serve.",
          failNext: "L'oggetto vero è da {villain}. Nel posto dopo dovete fare senza." },
        { id: "leave", label: "Lo lasciamo e andiamo via a testa alta", target: 4, dmg: 1,
          ok: "Il dono si offende e, per dispetto, indica la strada giusta. Non è vostro, ma sapete dove andare.",
          fail: "Il dono vi insegue. Morso d'orgoglio: chi voltava le spalle perde 1 cuore. Poi sparisce senza indicare niente.",
          okNext: "Avete la direzione, non l'oggetto. Il posto dopo è quello indicato dal dono offeso.",
          failNext: "Niente oggetto, niente direzione. Nel posto dopo camminate alla cieca." }
      ]
    }),
    ch({
      id: "c-night",
      kind: "stealth",
      who: "two",
      title: "Il giro notturno",
      player: "Dovete attraversare mentre il cattivo fa il giro di ronda. Se vi vede, è un problema.",
      master: "Siete a {location}.\n\n{villain} fa il giro notturno. {npc} russa. Male.\n\nDue di voi muovono il gruppo. Tira il primo. Se va, passate. Se no, scontro lampo e il cattivo sa che ci siete.",
      secret: "Successo: passaggio notturno pulito. Fallimento: 1 cuore e il cattivo è avvisato.",
      prompt: "Come vi muovete?",
      choices: [
        { id: "creep", label: "Ci muoviamo quando {npc} russa più forte", target: 4, dmg: 1,
          ok: "Il russare copre i passi. Geniale e orribile. Passate. {villain} non alza la testa.",
          fail: "Il russare si ferma proprio allora. Oh no. Chi camminava perde 1 cuore nello scontro lampo. {villain} vi ha visti.",
          okNext: "{villain} non sa che siete passati. Il posto dopo è ancora in modalità notte, calmo.",
          failNext: "{villain} vi ha visti. Il posto dopo è sveglio e ostile." },
        { id: "decoy", label: "Lasciamo un richiamo falso dall'altra parte", target: 5, dmg: 1,
          ok: "{villain} abbocca al falso. Voi no. Passate dal lato libero.",
          fail: "Abbocca a voi. Scontro lampo: chi ha messo il richiamo perde 1 cuore. Poi dovete correre.",
          okNext: "{villain} è ancora dal lato del richiamo. Il posto dopo è libero.",
          failNext: "State correndo. {villain} è alle calcagna. Il posto dopo è una fuga, non un arrivo." }
      ]
    }),
    ch({
      id: "c-storm2",
      kind: "danger",
      who: "one",
      title: "Il tetto che vola",
      player: "Il tetto sta per volare via. Sotto c'è qualcuno. Dovete tenere o tirare fuori la persona.",
      master: "Siete a {location}.\n\nIl tetto sta per volare via. Sotto c'è {npc}. {villain} tira raffiche apposta.\n\nSe tenete o salvate, {npc} è con voi dopo. Se fallite, un cuore e {npc} resta indietro.",
      secret: "Successo: NPC salvo e con voi. Fallimento: 1 cuore, NPC indietro.",
      prompt: "Cosa fate?",
      choices: [
        { id: "hold", label: "Teniamo il tetto tutti i secondi che servono", target: 5, dmg: 1,
          ok: "Il tetto resta. {npc} è salvo. Siete eroi da cantiere e vi segue.",
          fail: "Il tetto vince. Chi teneva perde 1 cuore di fatica. {npc} esce da solo, troppo tardi per seguirvi.",
          okNext: "{npc} è con voi. Nel posto dopo avete un paio di mani in più.",
          failNext: "{npc} è rimasto indietro. Nel posto dopo siete in meno." },
        { id: "run", label: "Tiriamo fuori {npc} e lasciamo volare il tetto", target: 4, dmg: 1,
          ok: "Salvataggio pulito. Il tetto fa un giro turistico. {npc} corre con voi.",
          fail: "Inciampo in uscita. Chi tira perde 1 cuore. {npc} è fuori, ma il tetto cadendo chiude la via dritta.",
          okNext: "Siete tutti fuori, insieme. La via dritta è ancora aperta.",
          failNext: "La via dritta è chiusa dal tetto. Dovete girare. {npc} zoppica dietro." }
      ]
    }),
    ch({
      id: "c-riddle2",
      kind: "puzzle",
      who: "one",
      title: "Tre porte",
      player: "Tre porte. Una porta all'oggetto, una all'amico, una dritta dal cattivo troppo presto. Dovete scegliere.",
      master: "Siete a {location}.\n\nTre porte. Una porta a {treasure}, una da {npc} alleato, una dritta da {villain} troppo presto.\n\nIl dado decide se indovinate «abbastanza». Se sbagliate, trappola e la porta che si apre è quella del cattivo.",
      secret: "Successo: porta utile (oggetto o alleato). Fallimento: 1 cuore e porta del cattivo (arrivate troppo presto, in svantaggio).",
      prompt: "Come scegliete la porta?",
      choices: [
        { id: "listen", label: "Ascoltiamo i ticchettii dietro le porte", target: 4, dmg: 1,
          ok: "Il ticchettio giusto. Porta onesta: trovate {treasure} oppure {npc} (quello che serve di più adesso).",
          fail: "Ticchettio bugiardo. Trappola: chi ascolta perde 1 cuore. Si apre la porta di {villain}, troppo presto.",
          okNext: "Avete trovato ciò che c'era dietro la porta onesta. Arrivate al posto dopo preparati.",
          failNext: "Siete usciti dalla porta di {villain}. Il posto dopo è già il suo terreno." },
        { id: "smell", label: "Seguiamo l'odore di merenda vera", target: 5, dmg: 1,
          ok: "L'odore non mente. Quasi mai. Porta buona.",
          fail: "Era odore di trappola al cioccolato. Chi annusa perde 1 cuore. Porta sbagliata.",
          okNext: "La porta della merenda vera vi ha messi sulla via giusta.",
          failNext: "La trappola al cioccolato vi ha aperti la porta sbagliata. {villain} è più vicino." }
      ]
    }),
    ch({
      id: "c-duel",
      kind: "danger",
      who: "one",
      title: "La sfida di coraggio",
      player: "Un servo del cattivo vi sfida. Non a duello di spade: a duello di coraggio. Dovete rispondere.",
      master: "Siete a {location}.\n\nUn servo di {villain} vi sfida: non spade, coraggio. {npc} fa da arbitro incerto.\n\nSe vincete, il servo se ne va e vi lascia la via. Se perdete, un cuore e il servo chiama rinforzi.",
      secret: "Successo: via libera. Fallimento: 1 cuore e rinforzi dopo.",
      prompt: "Come rispondete alla sfida?",
      choices: [
        { id: "stare", label: "Gara di sguardi, senza battere ciglio", target: 4, dmg: 1,
          ok: "L'altro batte le palpebre. Vittoria. Se ne va. La via è vostra.",
          fail: "Battete le palpebre voi. Chi guarda perde 1 cuore di smacco. Il servo fischia: arrivano rinforzi più tardi.",
          okNext: "Niente rinforzi. Il posto dopo è vuoto: potete attraversarlo in pace.",
          failNext: "I rinforzi stanno arrivando. Nel posto dopo non siete soli." },
        { id: "game", label: "Cambiamo gioco: una gara di equilibrio", target: 5, dmg: 1,
          ok: "Vince l'equilibrio. Il servo se ne va confuso e non chiama nessuno.",
          fail: "Caduta. Chi gareggiava perde 1 cuore. Il servo ride e chiama gli amici.",
          okNext: "Il servo è confuso e zitto. Via libera: nessuno vi segue.",
          failNext: "Gli amici del servo sono in cammino. Il posto dopo è più affollato." }
      ]
    }),
    ch({
      id: "c-map",
      kind: "explore",
      who: "one",
      title: "La mappa sospetta",
      player: "Trovate una mappa. Qualcuno giura che è vera. Puzza del cattivo. Vi fidate?",
      master: "Siete a {location}.\n\nTrovate una mappa. {npc} giura che è vera. Puzza di {villain}.\n\nSe la seguite bene, vi porta. Se è una trappola, 1 cuore e strada sbagliata. Se la ridisegnate, è brutta ma vostra.",
      secret: "Successo: mappa utile. Fallimento: 1 cuore e strada sbagliata.",
      prompt: "Vi fidate della mappa?",
      choices: [
        { id: "trust", label: "La seguiamo, ma con un occhio al cielo", target: 5, dmg: 1,
          ok: "Era vera al 70%. Basta. Vi porta al posto dopo dalla parte giusta.",
          fail: "Era vera al 10%. Trappola: chi legge perde 1 cuore. La mappa vi porta dove vuole {villain}.",
          okNext: "La mappa, abbastanza vera, vi ha messi sulla parte giusta.",
          failNext: "Siete dove vuole {villain}. Il posto dopo è una trappola già pronta." },
        { id: "redraw", label: "La ridisegniamo di testa nostra", target: 4, dmg: 1,
          ok: "La vostra mappa è brutta e corretta. Sapete dove andare.",
          fail: "Ancora più persi. Chi disegna perde 1 cuore di fatica. Camminate a caso.",
          okNext: "La mappa brutta è vostra. Nel posto dopo non vi perdete.",
          failNext: "Senza mappa vera, nel posto dopo girate a vuoto un po' prima di capire." }
      ]
    }),
    ch({
      id: "c-comfort",
      kind: "help",
      who: "one",
      title: "La paura contagiosa",
      player: "Un amico è in preda al panico. Se non lo calmate, il panico chiama il cattivo.",
      master: "Siete a {location}.\n\n{npc} è in preda al panico. Se non lo calmate, il panico chiama {villain}.\n\nSe si calma, resta con voi. Se le parole escono storte, il panico morde anche voi e {npc} scappa.",
      secret: "Successo: NPC calmo e con voi. Fallimento: 1 cuore e NPC in fuga (il cattivo è allertato).",
      prompt: "Come lo aiutate?",
      choices: [
        { id: "talk", label: "Parole basse, una mano sulla spalla", target: 4, dmg: 1,
          ok: "Il panico se ne va a fare un giro. {npc} resta e vi aiuta.",
          fail: "Le parole escono storte. Il panico morde anche voi: chi parla perde 1 cuore. {npc} scappa e il rumore chiama {villain}.",
          okNext: "{npc} è calmo e con voi. Il posto dopo non ha sentito niente.",
          failNext: "{npc} è in fuga. {villain} ha sentito il rumore. Il posto dopo è in allerta." },
        { id: "joke", label: "Una barzelletta nel momento sbagliato, che diventa giusto", target: 5, dmg: 1,
          ok: "Risata. Magia. {npc} si calma e il panico non chiama nessuno.",
          fail: "Barzelletta davvero sbagliata. Chi l'ha detta perde 1 cuore. {npc} piange più forte.",
          okNext: "La risata ha coperto tutto. Nessun allarme.",
          failNext: "I pianti si sono sentiti. {villain} sta venendo a vedere." }
      ]
    }),
    ch({
      id: "c-climb2",
      kind: "danger",
      who: "two",
      title: "La catena umana",
      player: "C'è un vuoto da superare. Serve una catena umana. Due di voi si organizzano.",
      master: "Siete a {location}.\n\nServe una catena umana per un vuoto. {npc} è troppo corto. {villain} tira ventate.\n\nDue persone, un tiro. Se regge, siete oltre. Se cede, cuori in meno e dovete scendere e girare.",
      secret: "Successo: oltre il vuoto. Fallimento: danno e giro sotto.",
      prompt: "Come vi organizzate?",
      choices: [
        { id: "chain", label: "Catena stretta, denti stretti", target: 4, dmg: 1,
          ok: "Funziona. Siete un bruco coraggioso. Oltre il vuoto, sulla via breve.",
          fail: "Cede un anello. Chi teneva perde 1 cuore. Dovete scendere e girare sotto.",
          okNext: "Via breve, oltre il vuoto. Il posto dopo è quello alto.",
          failNext: "Girate sotto. Il posto dopo è quello basso, più umido e lento." },
        { id: "throw", label: "Lanciamo il più leggero, poi il resto", target: 5, dmg: 2,
          ok: "Lancio da circo. Applausi interni. Siete tutti oltre, in un attimo.",
          fail: "Lancio da circo, atterraggio da no. Chi lancia perde 2 cuori. Poi il giro sotto, lenti.",
          okNext: "Siete oltre in un attimo. {villain} non ha visto il lancio.",
          failNext: "Il tonfo si è sentito. Girate sotto, e {villain} ha girato la testa." }
      ]
    }),
    ch({
      id: "c-shop",
      kind: "social",
      who: "one",
      title: "La bottega dei permessi",
      player: "Una bottega vende permessi per passare. Il bottegaio è parente del cattivo. Dovete ottenerne uno.",
      master: "Siete a {location}.\n\nUna bottega vende permessi. Il bottegaio è un cugino di {villain}, ma {npc} lo conosce.\n\nSe il permesso è vostro, passate da tutte le porte dopo. Se no, un cuore e niente timbro.",
      secret: "Successo: permesso per dopo. Fallimento: 1 cuore, niente permesso.",
      prompt: "Come ottenete il permesso?",
      choices: [
        { id: "polite", label: "Cortesia estrema e tre «per favore»", target: 4, dmg: 1,
          ok: "Permesso timbrato. Quasi legale. Le porte dopo vi riconoscono.",
          fail: "Troppa cortesia. Sospetto. Chi saluta perde 1 cuore. Niente timbro.",
          okNext: "Il permesso vale. Nel posto dopo le porte si aprono.",
          failNext: "Senza timbro, nel posto dopo le porte restano chiuse e dovete scavalcare." },
        { id: "cousin", label: "Chiediamo a {npc} di fare da garante", target: 5, dmg: 1,
          ok: "Garante accettato. Permesso in tasca. Le porte dopo vi riconoscono.",
          fail: "{npc} non è così famoso qui. Porta in faccia magica: chi chiede perde 1 cuore. Niente permesso.",
          okNext: "Con il garante, nel posto dopo siete «in regola».",
          failNext: "Senza garante e senza permesso. Nel posto dopo siete degli intrusi." }
      ]
    }),
    ch({
      id: "c-echo",
      kind: "explore",
      who: "one",
      title: "Gli echi che sbagliano",
      player: "Gli echi ripetono le istruzioni sbagliate. Il cattivo li ha addestrati. Dovete capire a chi credere.",
      master: "Siete a {location}.\n\nGli echi ripetono le istruzioni sbagliate. {npc} tappa le orecchie. {villain} ha addestrato gli echi.\n\nSe indovinate, uscite giusti. Se no, 1 cuore e l'eco bugiardo vi porta storti.",
      secret: "Successo: direzione vera. Fallimento: 1 cuore e direzione falsa.",
      prompt: "A chi credete?",
      choices: [
        { id: "eyes", label: "Occhi aperti, echi ignorati", target: 4, dmg: 1,
          ok: "Gli echi si offendono e tacciono. Uscite dove dicono gli occhi: la via vera.",
          fail: "Inciampate ignorando un avviso vero. Chi non ascoltava perde 1 cuore. Poi un eco vi spinge storti.",
          okNext: "La via vera, vista con gli occhi. Il posto dopo è quello.",
          failNext: "Un eco vi ha spinti storti. Il posto dopo non è quello che vedevate." },
        { id: "ears", label: "Ascoltiamo l'eco che sbaglia di meno", target: 5, dmg: 1,
          ok: "Trovate l'eco pentito. Vi guida alla via vera.",
          fail: "Era l'eco più bugiardo. Chi si fida perde 1 cuore. Vi porta dove vuole {villain}.",
          okNext: "L'eco pentito vi ha guidati. Siete sulla via vera.",
          failNext: "L'eco bugiardo vi ha consegnati al terreno di {villain}." }
      ]
    }),
    ch({
      id: "c-finalish",
      kind: "danger",
      who: "one",
      title: "L'allarme prematuro",
      player: "È partito un allarme. Se non lo spegnete, il cattivo sente. Dovete farlo zittire.",
      master: "Siete a {location}.\n\nQualcuno (forse {npc}) ha fatto partire un allarme. {villain} potrebbe sentire. Dovete spegnerlo.\n\nSe si spegne, restate nascosti. Se urla di più, 1 cuore e il cattivo è avvisato.",
      secret: "Successo: silenzio, ancora nascosti. Fallimento: 1 cuore e allarme sentito.",
      prompt: "Come spegnete l'allarme?",
      choices: [
        { id: "smash", label: "Un colpo deciso all'aggeggio", target: 4, dmg: 1,
          ok: "Silenzio. Un po' di pezzi per terra. {villain} non ha sentito.",
          fail: "L'aggeggio colpisce indietro: chi ha picchiato perde 1 cuore. Poi urla più forte. {villain} ha sentito.",
          okNext: "Silenzio. {villain} non sa niente. Il posto dopo è calmo.",
          failNext: "{villain} ha sentito. Il posto dopo è in allarme." },
        { id: "whisper", label: "Gli chiediamo di smettere, per favore", target: 6, dmg: 1,
          ok: "L'allarme aveva solo bisogno di essere ascoltato. Si spegne. Siete ancora nascosti.",
          fail: "Non ascolta. Urla di più. Chi sussurrava perde 1 cuore di stress. {villain} arriva.",
          okNext: "Ancora nascosti. Il posto dopo non sa che ci siete.",
          failNext: "{villain} arriva. Il posto dopo è uno scontro, non un arrivo silenzioso." }
      ]
    }),
    ch({
      id: "c-feast",
      kind: "moral",
      who: "two",
      title: "La tavola troppo piena",
      player: "C'è un banchetto. Mangiare darebbe forza, ma il cibo è firmato dal cattivo. Mangiate o no?",
      master: "Siete a {location}.\n\nC'è un banchetto. Mangiare dà forza, ma il cibo è firmato {villain}. {npc} ha già una forchetta in aria, piena di dubbi.\n\nSe l'assaggio è onesto, avete energia. Se è un tranello, un cuore e stomaco pieno di problemi. Se digiunate bene, siete lucidi. Se digiunate male, siete goffi.",
      secret: "Due strade. Successo: energia o lucidità. Fallimento: 1 cuore e svantaggio (pesantezza o fame goffa).",
      prompt: "Mangiate?",
      choices: [
        { id: "taste", label: "Un assaggio piccolo, da investigatori", target: 5, dmg: 1,
          ok: "Era buono e onesto, per una volta. Avete energia per la scena dopo.",
          fail: "Tranello dolce. Chi assaggia perde 1 cuore. Siete pesanti e lenti dopo.",
          okNext: "Avete energia. Nel posto dopo siete più in forma.",
          failNext: "Siete pesanti e lenti. Nel posto dopo i movimenti costano fatica." },
        { id: "skip", label: "Digiuniamo con dignità e andiamo", target: 4, dmg: 1,
          ok: "La fame vi rende lucidi. Passate. Niente tranelli in pancia.",
          fail: "La fame vi rende goffi. Inciampo: chi resisteva perde 1 cuore. Poi siete deboli.",
          okNext: "Lucidi e leggeri. Nel posto dopo notate di più.",
          failNext: "Goffi e deboli. Nel posto dopo inciampate più facilmente." }
      ]
    }),
    ch({
      id: "c-keyhunt",
      kind: "explore",
      who: "two",
      title: "La chiave nascosta",
      player: "Serve una chiave. Ce ne sono di false, messe dal cattivo. Dovete trovare quella vera.",
      master: "Siete a {location}.\n\nServe una chiave. {npc} ne ha vista una «più o meno lì». {villain} ne ha sparse di false.\n\nDue cercano, un tiro. Se è vera, aprite dopo. Se è falsa, scatta e restate senza chiave.",
      secret: "Successo: chiave vera per dopo. Fallimento: 1 cuore, niente chiave.",
      prompt: "Come cercate?",
      choices: [
        { id: "grid", label: "Setacciamo a griglia, da professionisti", target: 4, dmg: 1,
          ok: "Chiave vera. Fredda e onesta. Vi servirà tra poco.",
          fail: "Chiave falsa. Scatta: chi afferra perde 1 cuore. Le altre spariscono.",
          okNext: "Avete la chiave vera. Nel posto dopo c'è una porta che si apre.",
          failNext: "Senza chiave. Nel posto dopo la porta resta chiusa e dovete romperla o girare." },
        { id: "luck", label: "Chiudiamo gli occhi e affondiamo una mano", target: 6, dmg: 1,
          ok: "Fortuna insolente. Chiave vera, al primo colpo.",
          fail: "Mano in una trappola. Ovvio. Chi pesca perde 1 cuore. Niente chiave.",
          okNext: "Chiave in tasca. La porta dopo si apre senza sforzo.",
          failNext: "Trappola e niente chiave. La porta dopo è un problema." }
      ]
    }),
    ch({
      id: "c-wind",
      kind: "danger",
      who: "one",
      title: "Il vento che spinge",
      player: "Un vento voluto dal cattivo vi spinge verso il bordo. Dovete resistere o usarlo.",
      master: "Siete a {location}.\n\nUn vento voluto da {villain} vi spinge verso il bordo. {npc} si è già attaccato a un palo.\n\nSe resistete o lo cavalcate bene, andate dove volete voi. Se no, 1 cuore e il vento vi butta dove vuole lui.",
      secret: "Successo: direzione vostra. Fallimento: 1 cuore e direzione del cattivo.",
      prompt: "Che fate col vento?",
      choices: [
        { id: "resist", label: "Ci ancoriamo e aspettiamo", target: 4, dmg: 1,
          ok: "Il vento si stufa. Restate dove volevate. Poi camminate voi.",
          fail: "Vi sposta. Chi teneva il palo perde 1 cuore. Il vento vi scarica sul sentiero di {villain}.",
          okNext: "Siete dove volevate. Il posto dopo è la vostra scelta.",
          failNext: "Siete sul sentiero di {villain}. Il posto dopo è il suo." },
        { id: "ride", label: "Lo usiamo come spinta nella direzione giusta", target: 5, dmg: 1,
          ok: "Volo basso, atterraggio eroico. Proprio dove vi serviva.",
          fail: "Direzione sbagliata. Tonfo: chi «pilotava» perde 1 cuore. Atterrate dal lato del cattivo.",
          okNext: "Atterraggio nel punto giusto. Il posto dopo è quello.",
          failNext: "Atterraggio dal lato sbagliato. {villain} è più vicino del previsto." }
      ]
    }),
    ch({
      id: "c-promise",
      kind: "moral",
      who: "one",
      title: "La promessa",
      player: "Qualcuno chiede una promessa. Se la fate sul serio, vi aiuta. Se la voce trema, no.",
      master: "Siete a {location}.\n\n{npc} chiede una promessa: se la fate, vi aiuta contro {villain}. Se la rompete dopo, è un'altra storia. Ora conta se la pensate davvero (il dado).\n\nSe va, avete un aiuto. Se la voce trema, 1 cuore di vergogna magica e niente aiuto.",
      secret: "Successo: alleato. Fallimento: 1 cuore, niente aiuto.",
      prompt: "Promettete?",
      choices: [
        { id: "yes", label: "Promettiamo, e lo pensiamo davvero", target: 4, dmg: 1,
          ok: "La promessa si siede accanto a voi. {npc} vi aiuta da qui in poi.",
          fail: "La voce trema. Promessa rifiutata. Chi parlava perde 1 cuore di vergogna magica. {npc} si gira.",
          okNext: "{npc} è un alleato. Nel posto dopo avete il suo aiuto.",
          failNext: "{npc} si è girato. Nel posto dopo siete senza il suo aiuto." },
        { id: "later", label: "Chiediamo di parlarne dopo, da persone serie", target: 5, dmg: 1,
          ok: "{npc} rispetta la prudenza. Vi dà un aiuto piccolo, per ora.",
          fail: "La prudenza è letta come un no. Porta in faccia metaforica: chi rinvia perde 1 cuore. Niente aiuto.",
          okNext: "L'aiuto piccolo c'è. Nel posto dopo {npc} vi fa un cenno utile.",
          failNext: "Niente cenno, niente aiuto. Nel posto dopo {npc} non c'è." }
      ]
    })
  ];

  C.climax = [
    {
      id: "x-confront",
      title: "Faccia a faccia col cattivo",
      player: "Siete davanti al cattivo. Tutti tirano, uno alla volta. Serve che almeno la metà ce la faccia. Chi sbaglia perde un cuore.",
      master: "Siete a {location}.\n\nEcco {villain}. Tiene quello che cercate e ride della missione: {questName}.\n\n{npc} è nascosto, pronto a un piccolo aiuto.\n\nRegola: tirano TUTTI, uno alla volta. Chi sbaglia perde cuori. Se almeno la metà dei tiri riesce, vincete. Se no, dovete scappare. Se tutti arrivano a 0 cuori, l'avventura fallisce.",
      secret: "Tira tutto il gruppo. Serve almeno metà successi (arrotondati per eccesso). Ogni fallimento toglie cuori. 0 vivi = sconfitta. Meno della metà = fuga. Metà o più = vittoria.",
      prompt: "Come affrontate {villain}?",
      choices: [
        { id: "brave", label: "Andiamo avanti tutti insieme, con coraggio", target: 4, dmg: 1,
          ok: "Il coraggio fa breccia. {villain} indietreggia. Recuperate quello che serviva: {questGoal}.",
          fail: "Il coraggio non basta, stavolta. Dovete scappare con i cuori che restano. {questGoal} resta a {villain}, per oggi.",
          okNext: "",
          failNext: "" },
        { id: "smart", label: "Un piano furbo all'ultimo secondo", target: 5, dmg: 1,
          ok: "Il piano è ridicolo e funziona. {villain} resta a bocca aperta. La missione è compiuta.",
          fail: "Il piano è ridicolo e basta. Non funziona. Fuga. Tornerete un altro giorno.",
          okNext: "",
          failNext: "" },
        { id: "heart", label: "Parliamo al pezzo che è ancora buono, dentro {villain}", target: 6, dmg: 1,
          ok: "Qualcosa in {villain} esita. Ne approfittate e chiudete la missione.",
          fail: "Niente pezzo buono, oggi. Un colpo, e poi la fuga.",
          okNext: "",
          failNext: "" }
      ]
    },
    {
      id: "x-steal",
      title: "Il colpo finale",
      player: "Il cattivo è distratto. L'oggetto è lì. Tutti tirano. Serve almeno la metà dei successi.",
      master: "Siete a {location}.\n\n{villain} è distratto. {treasure} è lì. {npc} fa segno: ora o mai più. La missione è {questName}.\n\nTirano tutti. Metà successi (o più) per farcela. I fallimenti tolgono cuori. Se nessuno resta in piedi, è sconfitta. Se non arriva la metà, scappate.",
      secret: "Tiri di gruppo, metà successi per la vittoria. Altrimenti fuga o tpk.",
      prompt: "Come fate il colpo?",
      choices: [
        { id: "sneak", label: "Colpo silenzioso: prendiamo e via", target: 5, dmg: 1,
          ok: "Silenzio, oggetto, fuga giusta. {villain} si gira troppo tardi. Missione compiuta.",
          fail: "Un rumore. {villain} si gira. Dovete scappare a mani quasi vuote.",
          okNext: "",
          failNext: "" },
        { id: "distract", label: "Uno distrae, gli altri prendono", target: 4, dmg: 1,
          ok: "La distrazione è un capolavoro. Avete quello che serviva.",
          fail: "La distrazione è un flop. {villain} non ci casca. Fuga.",
          okNext: "",
          failNext: "" },
        { id: "charge", label: "Entriamo di slancio, che sia quel che sia", target: 4, dmg: 2,
          ok: "Caos vittorioso. Prendete {treasure} e chiudete la missione.",
          fail: "Caos doloroso. Cuori in meno e fuga. La missione resta aperta.",
          okNext: "",
          failNext: "" }
      ]
    },
    {
      id: "x-break",
      title: "Spezzare il trucco",
      player: "Il potere del cattivo sta in un trucco visibile. Dovete spezzarlo. Tirano tutti. Serve almeno la metà dei successi.",
      master: "Siete a {location}.\n\nIl potere di {villain} sta in un trucco visibile: un oggetto, un canto, un tappo. {npc} indica {treasure} come leva. La missione è {questName}.\n\nTirano tutti. Metà successi per spezzare il trucco. I fallimenti tolgono cuori.",
      secret: "Gruppo, metà successi = vittoria.",
      prompt: "Come spezzate il trucco?",
      choices: [
        { id: "break", label: "Lo rompiamo di netto", target: 4, dmg: 1,
          ok: "Si spezza. {villain} perde il ritmo. La missione è compiuta.",
          fail: "Non si spezza. Si vendica. Dovete scappare.",
          okNext: "",
          failNext: "" },
        { id: "turn", label: "Lo giriamo contro {villain}", target: 5, dmg: 1,
          ok: "Schiaffo di ironia magica. {villain} inciampa nel suo trucco. Voi vincete.",
          fail: "Rimbalza su di voi. Cuori in meno, poi la fuga.",
          okNext: "",
          failNext: "" },
        { id: "joke", label: "Lo rendiamo ridicolo, così smette di funzionare", target: 6, dmg: 1,
          ok: "Il ridicolo vince. Il trucco non funziona più. Missione chiusa.",
          fail: "Non era il tipo da ridicolo. Colpo, poi scappate.",
          okNext: "",
          failNext: "" }
      ]
    }
  ];

  C.openings = [
    "{master} è il master: legge questo quaderno ad alta voce. I giocatori ascoltano. Quando è il loro turno, scelgono cosa fare e tirano un dado a 6 facce.\n\nDOVE SIETE\n{world}. {worldHook}\n\nLA MISSIONE\n{questName}.\nIn pratica dovete recuperare {questGoal}.\n\nIL CATTIVO\n{villain}: {villainStyle}.\n\nCHI VI AIUTA\n{npc}: {npcQuirk}.\n\nCOSA TENERE A MENTE\nOgni avventuriero ha 3 cuori. Dopo un dado, se il numero è troppo basso si perde uno o più cuori E la storia prende l'altra strada (più difficile). A 0 cuori quel personaggio esce da QUESTA storia — niente sangue: sparisce come nelle fiabe — e si rivede a cena.\n\nFai dire a ogni giocatore il suo nome e il suo ruolo. Poi, quando sono pronti, inizia la prima prova."
  ];

  C.winEndings = [
    "Ce l'avete fatta.\n\n{villain} è sconfitto, o almeno in ritirata. Avete recuperato quello che serviva: {questGoal}.\n\nA {world} si torna a respirare. {npc} vi offre una merenda. Chi è ancora in gioco torna a casa con {treasure} e una storia da raccontare a cena.",
    "Il piano, anche se un po' storto, ha funzionato.\n\nMissione compiuta: {questName}. {villain} ha imparato (forse) la lezione. {npc} applaude. {world} vi deve un favore."
  ];

  C.failEndings = [
    "Nessuno è rimasto in gioco.\n\n{villain} tiene ancora {questGoal} e {world} resta storto.\n\nNon è la fine della famiglia: è la fine di QUESTA avventura. Si può sempre riprovare, un altro giorno, un altro racconto.",
    "C'è stato coraggio. Non c'è stata fortuna.\n\n{npc} chiude gli occhi. {villain} vince questo capitolo. L'avventura è fallita — e va bene: le storie vere hanno anche queste pagine."
  ];

  C.fleeEndings = [
    "Non avete vinto pulito: siete scappati con i cuori che restavano.\n\n{questGoal} è ancora in ballo, ma siete vivi. {npc} vi fa cenno: «Si torna. Un altro giorno.» {world} resta in sospeso.",
    "{villain} tiene il campo. Voi tenete la pelle.\n\nÈ una ritirata, non una vergogna. {treasure} è perso per ora. La famiglia, no."
  ];

  C.deathLines = [
    "{name} esce da questa storia: resta in una posa da eroe, come le statue. Si rivede a cena.",
    "{name} viene avvolto da una nebbia da capitolo chiuso. Fuori gioco, per stavolta.",
    "{name} sprofonda in un sonno magico troppo fondo. Per questa avventura, basta.",
    "{name} resta impigliato in una trappola di {villain}. Non può più seguire il gruppo, oggi.",
    "{name} si dissolve in stelline. Tornerà a cena, non in questa missione."
  ];

  root.AF_CONTENT = C;
})(typeof window !== "undefined" ? window : globalThis);
